/* 鬼滅之刃 英語修行 — 13 關（十二鬼月 + 鬼王無慘）
   每關 2+ 文法主題；10 例句(各配圖) + 10 單字 + 閱讀短文 + 題庫
   bank[].cat: "g"文法 / "v"單字 / "r"閱讀；抽題固定 閱讀5+文法5+單字5=15
   sentences[].img 對應 covers/Lxx_syy.jpg
*/
const LEVELS = [
/* ===== 1 下弦之伍 累 ===== */ {
  emoji:"🕸️", rank:"現在式·進行式", cover:"covers/cover01.jpg",
  title:"下弦之伍・累 Rui, Lower Five",
  focus:"文法焦點：一般現在式 + 現在進行式",
  reading:{title:"The Spider Mountain",
    en:"Rui is the Lower Rank Five of the Twelve Kizuki, the strongest demons who serve Muzan. He lives deep inside Mount Natagumo, a dark place covered with spider webs. Rui is lonely, so he uses his threads to control weaker demons and forces them to act like a family. But a false family built on fear is not real love. When Tanjiro and his friends climb the mountain, Rui is waiting for them. He cuts Tanjiro's blade with a single thread, because his webs are harder than steel. Tanjiro almost dies, yet he refuses to give up. With Nezuko's help and a new technique, he fights bravely. In the end, the Water Hashira, Giyu, arrives and defeats Rui in one clean strike. As Rui dies, he finally remembers his real human family and cries.",
    zh:"累是十二鬼月的下弦之伍，十二鬼月是侍奉無慘最強的鬼。他住在佈滿蜘蛛網、漆黑的那田蜘蛛山深處。累很孤獨，便用絲線控制弱小的鬼，逼他們扮演「家人」，但建立在恐懼上的假家庭並非真愛。炭治郎一行人上山時，累早已等候。他用一根絲線就割斷炭治郎的刀，因為他的網比鋼還硬。炭治郎險些喪命卻不放棄，靠著禰豆子與新招式勇敢奮戰。最後水柱義勇趕到，一刀擊敗累。累臨死時終於想起真正的人類家人，流下淚來。"},
  sentences:[
    {en:"Rui is the Lower Rank Five of the Twelve Kizuki.",zh:"累是十二鬼月的下弦之伍。",img:"covers/L01_s01.jpg"},
    {en:"He lives deep inside the dark spider mountain.",zh:"他住在漆黑的蜘蛛山深處。",img:"covers/L01_s02.jpg"},
    {en:"His threads cut steel and never break easily.",zh:"他的絲線能割斷鋼鐵，不易斷裂。",img:"covers/L01_s03.jpg"},
    {en:"Rui wants a real family who truly loves him.",zh:"累想要一個真正愛他的家人。",img:"covers/L01_s04.jpg"},
    {en:"The cold mountain always smells of fear and webs.",zh:"寒冷的山上總是瀰漫著恐懼與蛛網的氣味。",img:"covers/L01_s05.jpg"},
    {en:"Right now, Tanjiro is climbing the dark mountain.",zh:"此刻，炭治郎正在攀爬漆黑的山。",img:"covers/L01_s06.jpg"},
    {en:"Spider threads are falling from the tall trees.",zh:"蜘蛛絲正從高樹上落下。",img:"covers/L01_s07.jpg"},
    {en:"Rui is pulling the strings to control the demons.",zh:"累正拉動絲線操控那些鬼。",img:"covers/L01_s08.jpg"},
    {en:"Nezuko is protecting her brother from the webs.",zh:"禰豆子正保護哥哥免受蛛網之害。",img:"covers/L01_s09.jpg"},
    {en:"Giyu is coming to help the young slayers now.",zh:"義勇正趕來幫助年輕的隊士們。",img:"covers/L01_s10.jpg"}
  ],
  vocab:[
    {w:"rank",pos:"n.",d:"階級、位階"},{w:"control",pos:"v.",d:"控制"},
    {w:"thread",pos:"n.",d:"絲線"},{w:"victim",pos:"n.",d:"受害者"},
    {w:"web",pos:"n.",d:"蜘蛛網"},{w:"lonely",pos:"adj.",d:"孤獨的"},
    {w:"steel",pos:"n.",d:"鋼"},{w:"fear",pos:"n.",d:"恐懼"},
    {w:"pull",pos:"v.",d:"拉"},{w:"protect",pos:"v.",d:"保護"}
  ],
  grammar:[
    {rule:"<em>一般現在式</em>：表「習慣、事實」。第三人稱單數動詞加 <b>-s/-es</b>：live→<b>lives</b>。標誌詞：always, every day。"},
    {rule:"<em>現在進行式</em>：<b>be + V-ing</b>，表「此刻正在發生」。標誌詞：<b>now, right now, look!</b>。"},
    {rule:"判斷：habit/fact → 現在式；此刻動作 → 進行式。否定/疑問現在式用 <b>do/does</b>，進行式移動 <b>be</b> 動詞。"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"Rui ____ deep inside the mountain. (live)",opts:["lives","live","is living","lived"],a:0,ex:"事實，he→lives。"},
    {cat:"g",t:"選擇題",q:"His threads ____ steel easily. (cut, 事實)",opts:["cut","cuts","are cutting","cutting"],a:0,ex:"主詞 threads(複數)→原形 cut。"},
    {cat:"g",t:"是非題",q:"\"Rui want a real family.\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"he 應為 wants，故 False。"},
    {cat:"g",t:"選擇題",q:"____ Rui control the demons?",opts:["Do","Does","Is","Are"],a:1,ex:"第三人稱單數疑問用 Does。"},
    {cat:"g",t:"選擇題",q:"Look! Tanjiro ____ the mountain now.",opts:["climbs","is climbing","climb","climbed"],a:1,ex:"now/Look! → 進行式 is climbing。"},
    {cat:"g",t:"填空題",q:"Spider threads ____ (fall) from the trees right now.",opts:["are falling","fall","falls","fell"],a:0,ex:"right now → are falling。"},
    {cat:"g",t:"選擇題",q:"Nezuko ____ her brother at this moment.",opts:["protects","is protecting","protect","protected"],a:1,ex:"at this moment → is protecting。"},
    {cat:"g",t:"是非題",q:"\"Giyu is coming now.\" 是現在進行式。",opts:["正確 True","錯誤 False"],a:0,ex:"be + V-ing，正確。"},
    {cat:"v",t:"選擇題",q:"\"thread\" 的中文是？",opts:["絲線","威脅","寶座","麵包"],a:0,ex:"thread = 絲線。"},
    {cat:"v",t:"選擇題",q:"\"control\" 的意思是？",opts:["控制","收集","比較","治療"],a:0,ex:"control = 控制。"},
    {cat:"v",t:"選擇題",q:"\"lonely\" 的意思是？",opts:["快樂的","孤獨的","勇敢的","危險的"],a:1,ex:"lonely = 孤獨的。"},
    {cat:"v",t:"選擇題",q:"\"web\" 在此指？",opts:["網站","蜘蛛網","翅膀","水井"],a:1,ex:"此處 web = 蜘蛛網。"},
    {cat:"v",t:"選擇題",q:"\"victim\" 的中文是？",opts:["受害者","勝利者","志工","村民"],a:0,ex:"victim = 受害者。"},
    {cat:"v",t:"是非題",q:"\"fear\" 的意思是「勇氣」。",opts:["正確 True","錯誤 False"],a:1,ex:"fear = 恐懼，故 False。"},
    {cat:"v",t:"選擇題",q:"\"rank\" 在「下弦之伍」中指？",opts:["排隊","階級、位階","氣味","牧場"],a:1,ex:"rank = 階級、位階。"},
    {cat:"r",t:"選擇題",q:"What rank is Rui among the Twelve Kizuki?",opts:["Upper One","Lower Five","Upper Six","Lower One"],a:1,ex:"the Lower Rank Five。"},
    {cat:"r",t:"選擇題",q:"Why does Rui control weaker demons?",opts:["He is lonely and wants a family","To get money","To eat them","To make money"],a:0,ex:"He is lonely, so he uses his threads。"},
    {cat:"r",t:"選擇題",q:"Why could Rui cut Tanjiro's blade?",opts:["His webs are harder than steel","He had a gun","Tanjiro was asleep","The blade was old"],a:0,ex:"his webs are harder than steel。"},
    {cat:"r",t:"選擇題",q:"Who finally defeated Rui?",opts:["Zenitsu","Giyu, the Water Hashira","Inosuke","Nezuko"],a:1,ex:"the Water Hashira, Giyu, defeats Rui。"},
    {cat:"r",t:"是非題",q:"累臨死前想起了真正的人類家人。",opts:["正確 True","錯誤 False"],a:0,ex:"he finally remembers his real human family，True。"},
    {cat:"r",t:"是非題",q:"累的「家人」是建立在真愛之上。",opts:["正確 True","錯誤 False"],a:1,ex:"a false family built on fear，故 False。"}
  ]
},
/* ===== 2 下弦之陸 釜鵺 ===== */ {
  emoji:"🌑", rank:"過去式·過去進行式", cover:"covers/cover02.jpg",
  title:"下弦之陸・釜鵺 Kamanue, Lower Six",
  focus:"文法焦點：一般過去式 + 過去進行式",
  reading:{title:"The Lower Moons' Fear",
    en:"After Rui died, Muzan was very angry. He called the remaining Lower Moons to a secret meeting. Kamanue, the Lower Rank Six, was standing in the dark room while the other demons were waiting nervously. Muzan said that the Lower Moons were too weak, and one by one he destroyed them. While Kamanue was trying to explain himself, he was thinking of a way to escape. He told Muzan that he had a plan to grow stronger, but it was too late. Muzan did not listen. The other demons watched in terror as their master showed no mercy. That night taught every demon a hard lesson: in Muzan's world, weakness meant death. Only the Upper Moons, who were far stronger, were allowed to live and serve the demon king.",
    zh:"累死後，無慘大為震怒，召集殘存的下弦之鬼開祕密會議。下弦之陸釜鵺站在黑暗的房間裡，其他鬼則緊張地等待。無慘說下弦太弱，便一個接一個地將他們毀滅。當釜鵺正試圖為自己辯解時，他正想著逃跑的方法。他告訴無慘自己有變強的計畫，但為時已晚，無慘並不理會。其他鬼驚恐地看著主子毫不留情。那一夜給所有鬼上了殘酷的一課：在無慘的世界裡，軟弱就是死亡。只有遠比下弦強大的上弦之鬼才被允許存活、繼續侍奉鬼王。"},
  sentences:[
    {en:"After Rui died, Muzan became very angry.",zh:"累死後，無慘變得非常憤怒。",img:"covers/L02_s01.jpg"},
    {en:"He called the Lower Moons to a secret meeting.",zh:"他召集下弦之鬼開祕密會議。",img:"covers/L02_s02.jpg"},
    {en:"Muzan destroyed the weak demons one by one.",zh:"無慘一個接一個地毀滅弱小的鬼。",img:"covers/L02_s03.jpg"},
    {en:"Kamanue told Muzan that he had a plan.",zh:"釜鵺告訴無慘他有一個計畫。",img:"covers/L02_s04.jpg"},
    {en:"The other demons felt great fear that night.",zh:"那一夜其他鬼感到極大的恐懼。",img:"covers/L02_s05.jpg"},
    {en:"Kamanue was standing in the dark room.",zh:"釜鵺正站在黑暗的房間裡。",img:"covers/L02_s06.jpg"},
    {en:"The demons were waiting nervously for Muzan.",zh:"鬼們正緊張地等待無慘。",img:"covers/L02_s07.jpg"},
    {en:"While he was talking, he was thinking of escape.",zh:"當他正說話時，他正想著逃跑。",img:"covers/L02_s08.jpg"},
    {en:"Muzan was watching them with cold eyes.",zh:"無慘正用冰冷的眼神注視他們。",img:"covers/L02_s09.jpg"},
    {en:"They were trembling while their master spoke.",zh:"當主子說話時，他們正在發抖。",img:"covers/L02_s10.jpg"}
  ],
  vocab:[
    {w:"angry",pos:"adj.",d:"憤怒的"},{w:"meeting",pos:"n.",d:"會議"},
    {w:"destroy",pos:"v.",d:"摧毀（過去 destroyed）"},{w:"plan",pos:"n.",d:"計畫"},
    {w:"nervously",pos:"adv.",d:"緊張地"},{w:"escape",pos:"n./v.",d:"逃跑"},
    {w:"mercy",pos:"n.",d:"慈悲、寬恕"},{w:"terror",pos:"n.",d:"恐懼"},
    {w:"weakness",pos:"n.",d:"軟弱、弱點"},{w:"tremble",pos:"v.",d:"發抖"}
  ],
  grammar:[
    {rule:"<em>一般過去式</em>：過去發生且結束。規則加 <b>-ed</b>，不規則須背：become→became, tell→told, feel→felt。標誌詞：yesterday, that night, ago。"},
    {rule:"<em>過去進行式</em>：<b>was/were + V-ing</b>，過去某時正在進行。常與 <b>while</b> 連用。"},
    {rule:"組合：背景進行(過去進行) + 突發動作(過去簡單)：<b>While</b> he was talking, Muzan killed him。"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"After Rui died, Muzan ____ angry. (become)",opts:["became","becomes","is becoming","become"],a:0,ex:"過去式不規則 become→became。"},
    {cat:"g",t:"選擇題",q:"He ____ the weak demons one by one. (destroy)",opts:["destroys","destroyed","is destroying","destroy"],a:1,ex:"過去式 destroyed。"},
    {cat:"g",t:"填空題",q:"Kamanue ____ (tell) Muzan that he had a plan.",opts:["told","telled","tells","tell"],a:0,ex:"tell→told。"},
    {cat:"g",t:"是非題",q:"\"They feeled great fear.\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"feel→felt，故 False。"},
    {cat:"g",t:"選擇題",q:"Kamanue ____ in the dark room. (stand, 過去進行)",opts:["was standing","were standing","stood","stands"],a:0,ex:"he → was standing。"},
    {cat:"g",t:"選擇題",q:"The demons ____ nervously. (wait, 過去進行)",opts:["was waiting","were waiting","waited","wait"],a:1,ex:"they → were waiting。"},
    {cat:"g",t:"填空題",q:"While he ____ (talk), he was thinking of escape.",opts:["was talking","were talking","talked","talks"],a:0,ex:"while + 過去進行 was talking。"},
    {cat:"g",t:"是非題",q:"\"Muzan were watching them.\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"Muzan(單數) 應用 was，故 False。"},
    {cat:"v",t:"選擇題",q:"\"destroy\" 的意思是？",opts:["摧毀","建造","展示","保護"],a:0,ex:"destroy = 摧毀。"},
    {cat:"v",t:"選擇題",q:"\"mercy\" 的中文是？",opts:["慈悲、寬恕","市場","信息","金錢"],a:0,ex:"mercy = 慈悲。"},
    {cat:"v",t:"選擇題",q:"\"escape\" 的意思是？",opts:["逃跑","景色","昂貴","東方"],a:0,ex:"escape = 逃跑。"},
    {cat:"v",t:"選擇題",q:"\"nervously\" 的意思最接近？",opts:["緊張地","勇敢地","快樂地","大聲地"],a:0,ex:"nervously = 緊張地。"},
    {cat:"v",t:"選擇題",q:"\"tremble\" 的意思是？",opts:["發抖","旅行","交易","記得"],a:0,ex:"tremble = 發抖。"},
    {cat:"v",t:"是非題",q:"\"weakness\" 的相反詞是 strength。",opts:["正確 True","錯誤 False"],a:0,ex:"weakness(弱) ↔ strength(強)，True。"},
    {cat:"v",t:"選擇題",q:"\"terror\" 的意思最接近？",opts:["恐懼","旅程","老師","季節"],a:0,ex:"terror = 恐懼。"},
    {cat:"r",t:"選擇題",q:"Why did Muzan call the Lower Moons together?",opts:["To give them gifts","Because he was angry that they were weak","To make them Upper Moons","To have dinner"],a:1,ex:"Muzan was very angry... too weak。"},
    {cat:"r",t:"選擇題",q:"What did Muzan do to the Lower Moons?",opts:["Helped them train","Destroyed them one by one","Set them free","Made them leaders"],a:1,ex:"one by one he destroyed them。"},
    {cat:"r",t:"選擇題",q:"What was Kamanue thinking while he spoke?",opts:["About food","About a way to escape","About sleeping","About Nezuko"],a:1,ex:"he was thinking of a way to escape。"},
    {cat:"r",t:"選擇題",q:"What lesson did the demons learn?",opts:["Weakness meant death","Kindness wins","Sleep is important","Money is power"],a:0,ex:"weakness meant death。"},
    {cat:"r",t:"是非題",q:"只有上弦之鬼被允許存活。",opts:["正確 True","錯誤 False"],a:0,ex:"Only the Upper Moons... were allowed to live，True。"},
    {cat:"r",t:"是非題",q:"無慘聽從了釜鵺的計畫。",opts:["正確 True","錯誤 False"],a:1,ex:"Muzan did not listen，故 False。"}
  ]
},
/* ===== 3 下弦之肆 零余子 ===== */ {
  emoji:"🌀", rank:"未來式·can/could", cover:"covers/cover03.jpg",
  title:"下弦之肆・零余子 Mukago, Lower Four",
  focus:"文法焦點：未來式 (will / be going to) + 助動詞 can/could",
  reading:{title:"A Promise of Power",
    en:"Mukago was the Lower Rank Four. Like the other Lower Moons, she was terrified when Muzan appeared. \"I can become stronger if you give me more blood,\" she begged. \"I will catch more humans for you, I promise.\" But Muzan only asked a cold question: \"What will you do that the others could not?\" Mukago could not answer. She could feel her own death coming closer. In Muzan's eyes, a demon who could not win was useless. \"You are not going to serve me anymore,\" he said quietly. Far away, Tanjiro was training even harder, because he knew the road ahead would be dangerous. He could already use Water Breathing well, but he was going to learn to fight demons that were much stronger than Rui.",
    zh:"零余子是下弦之肆。和其他下弦一樣，無慘現身時她驚恐萬分。「只要給我更多血，我就能變強，」她哀求。「我會替你抓更多人類，我保證。」但無慘只冷冷地問：「你能做到其他鬼做不到的什麼事？」零余子答不出來，能感到死亡正逼近。在無慘眼中，無法取勝的鬼毫無用處。「你不會再侍奉我了，」他靜靜地說。遠方，炭治郎更加努力訓練，因他知道前路凶險。他已能熟練使用水之呼吸，但他打算學會對付比累強大得多的鬼。"},
  sentences:[
    {en:"\"I will catch more humans for you,\" Mukago begged.",zh:"「我會替你抓更多人類，」零余子哀求。",img:"covers/L03_s01.jpg"},
    {en:"\"What will you do for me?\" Muzan asked coldly.",zh:"「你會為我做什麼？」無慘冷冷地問。",img:"covers/L03_s02.jpg"},
    {en:"\"You are not going to serve me anymore.\"",zh:"「你不會再侍奉我了。」",img:"covers/L03_s03.jpg"},
    {en:"Tanjiro is going to learn stronger techniques.",zh:"炭治郎打算學會更強的招式。",img:"covers/L03_s04.jpg"},
    {en:"\"One day I will defeat every demon,\" he said.",zh:"「總有一天我會打敗每一隻鬼，」他說。",img:"covers/L03_s05.jpg"},
    {en:"\"I can become stronger,\" Mukago said with fear.",zh:"「我能變得更強，」零余子害怕地說。",img:"covers/L03_s06.jpg"},
    {en:"She could feel her own death coming closer.",zh:"她能感覺到死亡正逐漸逼近。",img:"covers/L03_s07.jpg"},
    {en:"Tanjiro can already use Water Breathing well.",zh:"炭治郎已能熟練使用水之呼吸。",img:"covers/L03_s08.jpg"},
    {en:"When he was weak, he could not cut the rock.",zh:"他虛弱時，無法劈開岩石。",img:"covers/L03_s09.jpg"},
    {en:"\"Could you teach me more, master?\" he asked.",zh:"「師父，您能多教我一些嗎？」他問。",img:"covers/L03_s10.jpg"}
  ],
  vocab:[
    {w:"catch",pos:"v.",d:"抓住（過去 caught）"},{w:"beg",pos:"v.",d:"哀求"},
    {w:"serve",pos:"v.",d:"侍奉、服務"},{w:"coldly",pos:"adv.",d:"冷淡地"},
    {w:"useless",pos:"adj.",d:"無用的"},{w:"closer",pos:"adj.",d:"更近的"},
    {w:"technique",pos:"n.",d:"技巧、招式"},{w:"dangerous",pos:"adj.",d:"危險的"},
    {w:"promise",pos:"v.",d:"保證、承諾"},{w:"already",pos:"adv.",d:"已經"}
  ],
  grammar:[
    {rule:"<em>未來式</em>：<b>will + 原形</b>(當下決定/承諾/預測)；<b>be going to + 原形</b>(既定計畫)。否定 will not = <b>won't</b>。"},
    {rule:"<em>can</em>：現在能力/許可，<b>can + 原形</b>，否定 can't。<em>could</em>：過去能力，或客氣請求 <b>Could you...?</b>"},
    {rule:"情態助動詞(can/could/will)後一律接 <b>原形動詞</b>，不隨主詞變化。"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"\"I ____ catch more humans for you.\" (承諾)",opts:["will","am going","going to","will to"],a:0,ex:"承諾用 will + 原形。"},
    {cat:"g",t:"選擇題",q:"\"You ____ serve me anymore.\" (be going to 否定)",opts:["are not going to","will not to","not going to","aren't going"],a:0,ex:"be not going to + 原形。"},
    {cat:"g",t:"填空題",q:"Tanjiro ____ (be going to) learn new techniques.",opts:["is going to","will to","are going to","going to"],a:0,ex:"he → is going to + 原形。"},
    {cat:"g",t:"是非題",q:"\"He will defeats every demon.\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"will 後接原形 defeat，故 False。"},
    {cat:"g",t:"選擇題",q:"\"I ____ become stronger.\" (現在能力)",opts:["can","cans","could to","can to"],a:0,ex:"can + 原形。"},
    {cat:"g",t:"選擇題",q:"When he was weak, he ____ cut the rock.",opts:["can't","couldn't","cannot","don't"],a:1,ex:"過去能力否定 couldn't。"},
    {cat:"g",t:"填空題",q:"\"____ you teach me more?\" (客氣請求)",opts:["Could","Can to","Do","Will to"],a:0,ex:"客氣請求 Could you...?"},
    {cat:"g",t:"是非題",q:"\"She can feels her death.\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"can 後接原形 feel，故 False。"},
    {cat:"v",t:"選擇題",q:"\"beg\" 的意思是？",opts:["哀求","開始","購買","攜帶"],a:0,ex:"beg = 哀求。"},
    {cat:"v",t:"選擇題",q:"\"serve\" 在此的意思是？",opts:["侍奉、服務","切開","儲存","保留"],a:0,ex:"serve = 侍奉、服務。"},
    {cat:"v",t:"選擇題",q:"\"useless\" 的意思是？",opts:["無用的","有用的","昂貴的","危險的"],a:0,ex:"useless = 無用的。"},
    {cat:"v",t:"選擇題",q:"\"technique\" 的中文是？",opts:["科技","技巧、招式","測驗","老師"],a:1,ex:"technique = 技巧、招式。"},
    {cat:"v",t:"選擇題",q:"The past form of \"catch\" is ____.",opts:["catched","caught","catchs","catches"],a:1,ex:"catch→caught。"},
    {cat:"v",t:"是非題",q:"\"dangerous\" 的意思是「安全的」。",opts:["正確 True","錯誤 False"],a:1,ex:"dangerous = 危險的，故 False。"},
    {cat:"v",t:"選擇題",q:"\"coldly\" 的意思是？",opts:["冷淡地","溫暖地","快速地","小心地"],a:0,ex:"coldly = 冷淡地。"},
    {cat:"r",t:"選擇題",q:"What did Mukago beg Muzan for?",opts:["More blood to become stronger","Money","A house","Freedom"],a:0,ex:"if you give me more blood。"},
    {cat:"r",t:"選擇題",q:"How did Muzan see a demon who could not win?",opts:["As useless","As a friend","As a leader","As clever"],a:0,ex:"a demon who could not win was useless。"},
    {cat:"r",t:"選擇題",q:"What was Tanjiro doing far away?",opts:["Sleeping","Training even harder","Selling charcoal","Hiding"],a:1,ex:"Tanjiro was training even harder。"},
    {cat:"r",t:"選擇題",q:"What was Tanjiro going to learn?",opts:["To cook","To fight much stronger demons","To paint","To swim"],a:1,ex:"going to learn to fight... stronger than Rui。"},
    {cat:"r",t:"是非題",q:"零余子能回答無慘的問題。",opts:["正確 True","錯誤 False"],a:1,ex:"Mukago could not answer，故 False。"},
    {cat:"r",t:"是非題",q:"炭治郎已能熟練使用水之呼吸。",opts:["正確 True","錯誤 False"],a:0,ex:"He could already use Water Breathing well，True。"}
  ]
},
/* ===== 4 下弦之參 病葉 ===== */ {
  emoji:"🍃", rank:"比較級·最高級", cover:"covers/cover04.jpg",
  title:"下弦之參・病葉 Wakuraba, Lower Three",
  focus:"文法焦點：形容詞比較級 + 最高級",
  reading:{title:"Faster Than the Rest",
    en:"Wakuraba was the Lower Rank Three. When Muzan began to kill the Lower Moons, Wakuraba decided to run. He was faster than the other demons, and for a moment he thought he could escape. But Muzan was the strongest demon in the world, far more powerful than any of them. No demon could move quicker than the king. Wakuraba's speed was useless. As he ran, his body began to break apart, and he turned to dust before he reached the door. It was the most terrible meeting the Lower Moons had ever known. Only the Upper Moons, who were much stronger and older, were safe. Among them, Kokushibo was the oldest and the deadliest. The night taught the demons that running was harder than facing the truth: in Muzan's world, only the strongest survived.",
    zh:"病葉是下弦之參。當無慘開始殺下弦時，病葉決定逃跑。他比其他鬼更快，一度以為能逃掉。但無慘是世上最強的鬼，遠比他們任何一個強大，沒有鬼能跑得比鬼王快。病葉的速度毫無用處。他奔逃時身體開始崩解，還沒到門口就化為塵土。那是下弦之鬼經歷過最可怕的會議。只有更強更年長的上弦之鬼安然無恙，其中黑死牟最年長也最致命。那一夜讓鬼明白：逃跑比面對真相更難——在無慘的世界裡，只有最強者能存活。"},
  sentences:[
    {en:"Wakuraba was faster than the other Lower Moons.",zh:"病葉比其他下弦之鬼更快。",img:"covers/L04_s01.jpg"},
    {en:"Muzan was stronger than any demon alive.",zh:"無慘比任何活著的鬼都更強。",img:"covers/L04_s02.jpg"},
    {en:"The Upper Moons are more powerful than the Lower Moons.",zh:"上弦之鬼比下弦之鬼更強大。",img:"covers/L04_s03.jpg"},
    {en:"Escaping was harder than fighting the king.",zh:"逃跑比對抗鬼王更難。",img:"covers/L04_s04.jpg"},
    {en:"Fear made the night darker than before.",zh:"恐懼讓那夜比以往更黑暗。",img:"covers/L04_s05.jpg"},
    {en:"Muzan is the strongest demon in the world.",zh:"無慘是世上最強的鬼。",img:"covers/L04_s06.jpg"},
    {en:"Wakuraba was the fastest of the Lower Moons.",zh:"病葉是下弦之鬼中最快的。",img:"covers/L04_s07.jpg"},
    {en:"That was the most terrible meeting of all.",zh:"那是所有會議中最可怕的一次。",img:"covers/L04_s08.jpg"},
    {en:"Kokushibo is the oldest of the Upper Moons.",zh:"黑死牟是上弦之鬼中最年長的。",img:"covers/L04_s09.jpg"},
    {en:"Tanjiro trained with the bravest heart of all.",zh:"炭治郎以最勇敢的心訓練。",img:"covers/L04_s10.jpg"}
  ],
  vocab:[
    {w:"powerful",pos:"adj.",d:"強大的"},{w:"afraid",pos:"adj.",d:"害怕的"},
    {w:"escape",pos:"v.",d:"逃跑"},{w:"terrible",pos:"adj.",d:"可怕的"},
    {w:"brave",pos:"adj.",d:"勇敢的"},{w:"alive",pos:"adj.",d:"活著的"},
    {w:"speed",pos:"n.",d:"速度"},{w:"survive",pos:"v.",d:"存活"},
    {w:"dust",pos:"n.",d:"塵土"},{w:"deadly",pos:"adj.",d:"致命的"}
  ],
  grammar:[
    {rule:"<em>比較級</em>(兩者)：短形容詞+<b>-er</b>+than(fast→faster)；長形容詞用 <b>more</b>(powerful→more powerful)。不規則 good→better, bad→worse。"},
    {rule:"<em>最高級</em>(三者以上)：<b>the</b>+短形容詞<b>-est</b>(fast→the fastest)；長形容詞 <b>the most</b>。不規則 good→the best, bad→the worst。"},
    {rule:"字尾變化：big→bigger/biggest；happy→happier/happiest；brave→braver/bravest。"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"Wakuraba was ____ than the others. (fast)",opts:["faster","more fast","fastest","fast"],a:0,ex:"fast→faster + than。"},
    {cat:"g",t:"選擇題",q:"The Upper Moons are ____ than the Lower ones. (powerful)",opts:["powerfuler","more powerful","most powerful","powerful"],a:1,ex:"長形容詞 more powerful。"},
    {cat:"g",t:"填空題",q:"Escaping was ____ (hard) than fighting.",opts:["harder","more hard","hardest","hard"],a:0,ex:"hard→harder。"},
    {cat:"g",t:"是非題",q:"\"This is more darker than before.\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"darker 已是比較級，不可加 more，故 False。"},
    {cat:"g",t:"選擇題",q:"Muzan is ____ demon in the world. (strong)",opts:["the strongest","the most strong","stronger","strong"],a:0,ex:"strong→the strongest。"},
    {cat:"g",t:"選擇題",q:"That was ____ meeting of all. (terrible)",opts:["the terriblest","the most terrible","more terrible","terrible"],a:1,ex:"長形容詞 the most terrible。"},
    {cat:"g",t:"填空題",q:"Kokushibo is ____ (old) of the Upper Moons.",opts:["the oldest","the most old","older","old"],a:0,ex:"old→the oldest。"},
    {cat:"g",t:"是非題",q:"\"good\" 的最高級是 the best。",opts:["正確 True","錯誤 False"],a:0,ex:"good→better→the best，True。"},
    {cat:"v",t:"選擇題",q:"\"powerful\" 的意思是？",opts:["強大的","貧窮的","禮貌的","可能的"],a:0,ex:"powerful = 強大的。"},
    {cat:"v",t:"選擇題",q:"\"escape\" 的中文是？",opts:["逃跑","景色","昂貴","討論"],a:0,ex:"escape = 逃跑。"},
    {cat:"v",t:"選擇題",q:"\"alive\" 的意思是？",opts:["活著的","害怕的","聰明的","昂貴的"],a:0,ex:"alive = 活著的。"},
    {cat:"v",t:"選擇題",q:"\"deadly\" 的意思最接近？",opts:["致命的","可愛的","每日的","深的"],a:0,ex:"deadly = 致命的。"},
    {cat:"v",t:"選擇題",q:"\"dust\" 的中文是？",opts:["塵土","桌子","信任","黃昏"],a:0,ex:"dust = 塵土。"},
    {cat:"v",t:"是非題",q:"\"brave\" 的意思是「膽小的」。",opts:["正確 True","錯誤 False"],a:1,ex:"brave = 勇敢的，故 False。"},
    {cat:"v",t:"選擇題",q:"\"speed\" 與哪個形容詞相關？",opts:["fast","slow only","tall","kind"],a:0,ex:"speed(速度) 與 fast 相關。"},
    {cat:"r",t:"選擇題",q:"What did Wakuraba decide to do?",opts:["Fight Muzan","Run away","Join the slayers","Sleep"],a:1,ex:"Wakuraba decided to run。"},
    {cat:"r",t:"選擇題",q:"Why was his speed useless?",opts:["He was tired","No demon could move quicker than Muzan","He had no legs","He was caught in a web"],a:1,ex:"No demon could move quicker than the king。"},
    {cat:"r",t:"選擇題",q:"What happened to Wakuraba before he reached the door?",opts:["He escaped","He turned to dust","He became Upper Moon","He fell asleep"],a:1,ex:"he turned to dust。"},
    {cat:"r",t:"選擇題",q:"Who was the oldest and deadliest Upper Moon?",opts:["Akaza","Kokushibo","Doma","Daki"],a:1,ex:"Kokushibo was the oldest and the deadliest。"},
    {cat:"r",t:"是非題",q:"在無慘的世界裡只有最強者能存活。",opts:["正確 True","錯誤 False"],a:0,ex:"only the strongest survived，True。"},
    {cat:"r",t:"是非題",q:"病葉成功逃出了會議。",opts:["正確 True","錯誤 False"],a:1,ex:"he turned to dust before he reached the door，故 False。"}
  ]
},
/* ===== 5 下弦之貳 轆轤 ===== */ {
  emoji:"⚙️", rank:"完成式·must/should", cover:"covers/cover05.jpg",
  title:"下弦之貳・轆轤 Rokuro, Lower Two",
  focus:"文法焦點：現在完成式 + 助動詞 must/should/have to",
  reading:{title:"Loyalty Is Not Enough",
    en:"Rokuro was the Lower Rank Two. He has served Muzan for many years and has killed many humans, so he believed he was safe. \"I have always obeyed you,\" he said proudly. But Muzan was not pleased. \"You have never defeated a Hashira,\" he answered coldly. \"A demon must be useful, or it must die.\" Rokuro understood that loyalty alone was not enough. \"You should have become stronger,\" Muzan said. \"You have wasted my blood.\" In the world of demons, every servant has to bring real results. Far away, the Demon Slayers learned the same hard truth in a kinder way: a warrior should never stop training, and must always protect the weak. Tanjiro has grown much stronger since the spider mountain, and he is ready for greater battles.",
    zh:"轆轤是下弦之貳。他已侍奉無慘多年、殺過許多人類，便以為自己安全。「我一向都服從您，」他驕傲地說。但無慘並不滿意。「你從未打敗過任何一柱，」他冷冷回答。「鬼必須有用，否則就得死。」轆轤明白光有忠誠並不夠。「你早該變得更強，」無慘說。「你浪費了我的血。」在鬼的世界裡，每個僕人都得拿出真正的成果。遠方，鬼殺隊以較溫和的方式學到同樣的硬道理：戰士不該停止訓練，且必須永遠保護弱者。炭治郎自蜘蛛山後已強大許多，準備迎接更大的戰鬥。"},
  sentences:[
    {en:"Rokuro has served Muzan for many years.",zh:"轆轤已侍奉無慘多年。",img:"covers/L05_s01.jpg"},
    {en:"\"I have killed hundreds of humans,\" he said.",zh:"「我已殺過數百名人類，」他說。",img:"covers/L05_s02.jpg"},
    {en:"\"You have never defeated a Hashira,\" Muzan replied.",zh:"「你從未打敗過任何一柱，」無慘回答。",img:"covers/L05_s03.jpg"},
    {en:"The Lower Moons have already lost Muzan's trust.",zh:"下弦之鬼已失去無慘的信任。",img:"covers/L05_s04.jpg"},
    {en:"Tanjiro has grown stronger since the spider mountain.",zh:"炭治郎自蜘蛛山後已變得更強。",img:"covers/L05_s05.jpg"},
    {en:"\"A demon must obey the king,\" Muzan said.",zh:"「鬼必須服從鬼王，」無慘說。",img:"covers/L05_s06.jpg"},
    {en:"\"You should not question my orders.\"",zh:"「你不該質疑我的命令。」",img:"covers/L05_s07.jpg"},
    {en:"Slayers must protect humans with their lives.",zh:"隊士必須以生命保護人類。",img:"covers/L05_s08.jpg"},
    {en:"\"You have to be useful, or you will die.\"",zh:"「你必須有用，否則就會死。」",img:"covers/L05_s09.jpg"},
    {en:"\"A warrior should never stop training.\"",zh:"「戰士不該停止訓練。」",img:"covers/L05_s10.jpg"}
  ],
  vocab:[
    {w:"serve",pos:"v.",d:"侍奉、服務"},{w:"loyal",pos:"adj.",d:"忠誠的"},
    {w:"obey",pos:"v.",d:"服從"},{w:"order",pos:"n.",d:"命令"},
    {w:"trust",pos:"n.",d:"信任"},{w:"useful",pos:"adj.",d:"有用的"},
    {w:"waste",pos:"v.",d:"浪費"},{w:"question",pos:"v.",d:"質疑"},
    {w:"result",pos:"n.",d:"成果、結果"},{w:"proudly",pos:"adv.",d:"驕傲地"}
  ],
  grammar:[
    {rule:"<em>現在完成式</em>：<b>have/has + 過去分詞(p.p.)</b>，表經驗或影響至今。標誌詞：already, never, ever, since, for。"},
    {rule:"不規則 p.p.：kill→killed, serve→served, grow→grown, lose→lost, defeat→defeated。he/she/it 用 has。"},
    {rule:"<em>must</em>(強烈義務/必須)、<em>have to</em>(外在規定)、<em>should</em>(建議/應該)，後接 <b>原形動詞</b>；must not=禁止。"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"Rokuro ____ Muzan for many years. (serve, 完成式)",opts:["has served","have served","served","serves"],a:0,ex:"he + has + p.p. served，for→完成式。"},
    {cat:"g",t:"選擇題",q:"\"You have never ____ a Hashira.\" (defeat)",opts:["defeat","defeated","defeats","defeating"],a:1,ex:"完成式用 p.p. defeated。"},
    {cat:"g",t:"填空題",q:"Tanjiro ____ (grow) stronger since then.",opts:["has grown","have grown","grew","grows"],a:0,ex:"he → has grown。"},
    {cat:"g",t:"是非題",q:"\"The demons have already lost his trust.\" 文法正確。",opts:["正確 True","錯誤 False"],a:0,ex:"already + 完成式，正確。"},
    {cat:"g",t:"選擇題",q:"\"A demon ____ obey the king.\" (強烈義務)",opts:["must","should not","don't have to","can't"],a:0,ex:"強烈義務用 must。"},
    {cat:"g",t:"選擇題",q:"\"You ____ question my orders.\" (不該)",opts:["should not","must","have to","don't have"],a:0,ex:"「不該」用 should not。"},
    {cat:"g",t:"填空題",q:"Slayers ____ protect humans. (必須, must)",opts:["must","should not","don't have to","can't"],a:0,ex:"義務用 must + 原形。"},
    {cat:"g",t:"是非題",q:"\"You must to be useful.\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"must 後不加 to，故 False。"},
    {cat:"v",t:"選擇題",q:"\"loyal\" 的意思是？",opts:["忠誠的","懶惰的","當地的","可愛的"],a:0,ex:"loyal = 忠誠的。"},
    {cat:"v",t:"選擇題",q:"\"obey\" 的中文是？",opts:["服從","反對","得到","購買"],a:0,ex:"obey = 服從。"},
    {cat:"v",t:"選擇題",q:"\"useful\" 的意思是？",opts:["有用的","無用的","美麗的","危險的"],a:0,ex:"useful = 有用的。"},
    {cat:"v",t:"選擇題",q:"\"waste\" (動詞) 的意思是？",opts:["浪費","等待","清洗","想要"],a:0,ex:"waste = 浪費。"},
    {cat:"v",t:"選擇題",q:"\"result\" 的中文是？",opts:["成果、結果","休息","規則","路線"],a:0,ex:"result = 成果、結果。"},
    {cat:"v",t:"是非題",q:"\"question\" 當動詞可指「質疑」。",opts:["正確 True","錯誤 False"],a:0,ex:"question(v) = 質疑，True。"},
    {cat:"v",t:"選擇題",q:"\"trust\" (名詞) 的意思是？",opts:["信任","卡車","嘗試","真相"],a:0,ex:"trust = 信任。"},
    {cat:"r",t:"選擇題",q:"Why did Rokuro think he was safe?",opts:["He had served and killed for years","He was the strongest","He had a weapon","He hid well"],a:0,ex:"served... and killed many humans, so he believed he was safe。"},
    {cat:"r",t:"選擇題",q:"What had Rokuro never done?",opts:["Eaten a human","Defeated a Hashira","Served Muzan","Killed anyone"],a:1,ex:"You have never defeated a Hashira。"},
    {cat:"r",t:"選擇題",q:"According to Muzan, what must a demon be?",opts:["Kind","Useful","Quiet","Old"],a:1,ex:"A demon must be useful, or it must die。"},
    {cat:"r",t:"選擇題",q:"What truth did the slayers learn in a kinder way?",opts:["Never stop training and protect the weak","Money is power","Demons are friends","Sleep is best"],a:0,ex:"should never stop training, and must always protect the weak。"},
    {cat:"r",t:"是非題",q:"轆轤明白光有忠誠並不足夠。",opts:["正確 True","錯誤 False"],a:0,ex:"loyalty alone was not enough，True。"},
    {cat:"r",t:"是非題",q:"無慘對轆轤的忠誠感到非常滿意。",opts:["正確 True","錯誤 False"],a:1,ex:"Muzan was not pleased，故 False。"}
  ]
},
/* ===== 6 下弦之壹 魘夢 ===== */ {
  emoji:"🚂", rank:"不定詞·動名詞", cover:"covers/cover06.jpg",
  title:"下弦之壹・魘夢 Enmu, Lower One",
  focus:"文法焦點：不定詞 to V + 動名詞 V-ing",
  reading:{title:"The Mugen Train",
    en:"Enmu was the Lower Rank One, the only Lower Moon that Muzan allowed to live. Muzan gave him more blood, so Enmu became very strong. His power was to make people fall asleep and to control their dreams. On the Mugen Train, he wanted to eat the dreams of hundreds of sleeping passengers. Sleeping deeply was his trap, because waking up felt impossible. To escape a dream, a person had to do something terrible: cut his own neck inside the dream. Tanjiro kept trying to wake up again and again. He hated hurting himself, but saving the passengers was more important than his fear. Enmu enjoyed watching people suffer, yet he did not expect such brave slayers. By working together and never giving up, Tanjiro and his friends finally stopped the demon and protected everyone on the train.",
    zh:"魘夢是下弦之壹，是唯一被無慘允許存活的下弦之鬼。無慘給他更多血，使他變得非常強。他的能力是讓人入睡並操控夢境。在無限列車上，他想吞食數百名沉睡乘客的夢。沉睡是他的陷阱，因為醒來似乎不可能。要逃離夢境，人必須做一件可怕的事：在夢中割斷自己的脖子。炭治郎一次又一次嘗試醒來。他討厭傷害自己，但拯救乘客比恐懼更重要。魘夢享受看人受苦，卻沒料到隊士如此勇敢。靠著合作、永不放棄，炭治郎和夥伴終於阻止了這隻鬼，守護了列車上的每個人。"},
  sentences:[
    {en:"Enmu wanted to please Muzan more than anyone.",zh:"魘夢想比任何人都更取悅無慘。",img:"covers/L06_s01.jpg"},
    {en:"He used his power to make people fall asleep.",zh:"他用能力讓人入睡。",img:"covers/L06_s02.jpg"},
    {en:"Tanjiro tried to wake up from the dream.",zh:"炭治郎試著從夢中醒來。",img:"covers/L06_s03.jpg"},
    {en:"To escape a dream, you must cut your own neck.",zh:"要逃離夢境，你必須割斷自己的脖子。",img:"covers/L06_s04.jpg"},
    {en:"The slayers needed to protect the passengers.",zh:"隊士們需要保護乘客。",img:"covers/L06_s05.jpg"},
    {en:"Sleeping deeply was the demon's clever trap.",zh:"沉睡是這隻鬼狡猾的陷阱。",img:"covers/L06_s06.jpg"},
    {en:"Enmu enjoyed eating people's happy dreams.",zh:"魘夢享受吞食人們的美夢。",img:"covers/L06_s07.jpg"},
    {en:"Tanjiro kept fighting without giving up.",zh:"炭治郎持續奮戰，不放棄。",img:"covers/L06_s08.jpg"},
    {en:"Waking up was the only way to survive.",zh:"醒來是唯一的生路。",img:"covers/L06_s09.jpg"},
    {en:"They stopped the demon by working together.",zh:"他們靠著合作阻止了這隻鬼。",img:"covers/L06_s10.jpg"}
  ],
  vocab:[
    {w:"please",pos:"v.",d:"取悅、使高興"},{w:"asleep",pos:"adj.",d:"睡著的"},
    {w:"dream",pos:"n.",d:"夢"},{w:"trap",pos:"n.",d:"陷阱"},
    {w:"passenger",pos:"n.",d:"乘客"},{w:"neck",pos:"n.",d:"脖子"},
    {w:"survive",pos:"v.",d:"存活"},{w:"deeply",pos:"adv.",d:"深深地"},
    {w:"suffer",pos:"v.",d:"受苦"},{w:"enjoy",pos:"v.",d:"享受"}
  ],
  grammar:[
    {rule:"<em>不定詞 to + 原形</em>：表目的(為了…)，或接於 want, need, try, hope, decide, would like 之後。"},
    {rule:"<em>動名詞 V-ing</em>：當主詞/受詞；接於 enjoy, keep, finish, hate, like, mind 之後；<b>介系詞</b>後也用 V-ing。"},
    {rule:"句型 <b>by + V-ing</b>(藉由…)；<b>without + V-ing</b>(不…)。"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"Enmu wanted ____ Muzan. (please)",opts:["to please","please","pleasing","pleased"],a:0,ex:"want + to V。"},
    {cat:"g",t:"選擇題",q:"He used his power ____ people sleep. (目的, make)",opts:["to make","make","making","made"],a:0,ex:"表目的 to + 原形。"},
    {cat:"g",t:"填空題",q:"The slayers needed ____ (protect) the passengers.",opts:["to protect","protect","protecting","protected"],a:0,ex:"need + to V。"},
    {cat:"g",t:"是非題",q:"\"Tanjiro tried wake up.\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"try 後應接 to wake，故 False。"},
    {cat:"g",t:"選擇題",q:"____ deeply was the demon's trap. (sleep, 當主詞)",opts:["Sleeping","Sleep","To sleeping","Slept"],a:0,ex:"當主詞用動名詞 Sleeping。"},
    {cat:"g",t:"選擇題",q:"Enmu enjoyed ____ dreams. (eat)",opts:["eat","to eat","eating","ate"],a:2,ex:"enjoy + V-ing。"},
    {cat:"g",t:"填空題",q:"Tanjiro kept ____ (fight) without giving up.",opts:["fighting","to fight","fight","fought"],a:0,ex:"keep + V-ing。"},
    {cat:"g",t:"是非題",q:"\"They stopped the demon by working together.\" 文法正確。",opts:["正確 True","錯誤 False"],a:0,ex:"by + V-ing，正確。"},
    {cat:"v",t:"選擇題",q:"\"asleep\" 的意思是？",opts:["睡著的","醒著的","害怕的","疲累的"],a:0,ex:"asleep = 睡著的。"},
    {cat:"v",t:"選擇題",q:"\"trap\" 的中文是？",opts:["陷阱","旅行","抹布","地圖"],a:0,ex:"trap = 陷阱。"},
    {cat:"v",t:"選擇題",q:"\"neck\" 的意思是？",opts:["脖子","手肘","膝蓋","下巴"],a:0,ex:"neck = 脖子。"},
    {cat:"v",t:"選擇題",q:"\"suffer\" 的意思最接近？",opts:["受苦","成功","供應","建議"],a:0,ex:"suffer = 受苦。"},
    {cat:"v",t:"選擇題",q:"\"please\" 當動詞的意思是？",opts:["取悅、使高興","請求","放置","付款"],a:0,ex:"please(v) = 取悅。"},
    {cat:"v",t:"是非題",q:"\"deeply\" 的意思是「深深地」。",opts:["正確 True","錯誤 False"],a:0,ex:"deeply = 深深地，True。"},
    {cat:"v",t:"選擇題",q:"\"passenger\" 的中文是？",opts:["乘客","駕駛","行人","站長"],a:0,ex:"passenger = 乘客。"},
    {cat:"r",t:"選擇題",q:"Why did Muzan let Enmu live?",opts:["Enmu was kind","Muzan gave him more blood and power","Enmu hid","Enmu paid him"],a:1,ex:"the only Lower Moon Muzan allowed to live; gave him more blood。"},
    {cat:"r",t:"選擇題",q:"What was Enmu's power?",opts:["Fire","To make people sleep and control dreams","To fly","To read minds"],a:1,ex:"make people fall asleep and to control their dreams。"},
    {cat:"r",t:"選擇題",q:"How could a person escape the dream?",opts:["By sleeping more","By cutting his own neck in the dream","By eating","By running"],a:1,ex:"cut his own neck inside the dream。"},
    {cat:"r",t:"選擇題",q:"Why did Tanjiro keep hurting himself?",opts:["He liked pain","Saving the passengers mattered more than his fear","Enmu forced him","He was dreaming nicely"],a:1,ex:"saving the passengers was more important than his fear。"},
    {cat:"r",t:"是非題",q:"魘夢是唯一被無慘允許存活的下弦之鬼。",opts:["正確 True","錯誤 False"],a:0,ex:"the only Lower Moon that Muzan allowed to live，True。"},
    {cat:"r",t:"是非題",q:"隊士們最後沒能阻止魘夢。",opts:["正確 True","錯誤 False"],a:1,ex:"finally stopped the demon，故 False。"}
  ]
},
/* ===== 7 上弦之陸 墮姬與妓夫太郎 ===== */ {
  emoji:"🎎", rank:"被動·關係代名詞", cover:"covers/cover07.jpg",
  title:"上弦之陸・墮姬與妓夫太郎 Daki & Gyutaro",
  focus:"文法焦點：被動語態 + 關係代名詞",
  reading:{title:"The Upper Six of the Entertainment District",
    en:"The Upper Rank Six was actually two demons: Daki, a beautiful young woman, and her brother Gyutaro, who was hidden inside her body. For years, many people were taken and eaten in the entertainment district. The Sound Hashira, Tengen Uzui, led the mission, and he was helped by Tanjiro, Zenitsu, and Inosuke. Daki used deadly sashes which could crush whole buildings. The slayers learned a secret: to win, both demon heads had to be cut at the same time. Gyutaro, whose hatred made him strong, was the real danger. The battle was long and many fighters were badly hurt. But the slayers who never gave up finally beheaded both demons together. As they died, the brother and sister remembered their sad human past, and the district was saved at last.",
    zh:"上弦之陸其實是兩隻鬼：美麗的少女墮姬，與藏在她體內的哥哥妓夫太郎。多年來，許多人在花街被擄走、吞食。音柱宇髓天元帶領這次任務，由炭治郎、善逸、伊之助協助。墮姬使用能粉碎整棟建築的致命腰帶。隊士們得知祕密：要取勝，必須同時斬下兩顆鬼首。憎恨使其強大的妓夫太郎才是真正的威脅。戰鬥漫長，許多戰士身受重傷。但永不放棄的隊士終於同時斬下兩鬼之首。臨死時，兄妹想起悲傷的人類過往，花街終於得救。"},
  sentences:[
    {en:"Many people were taken by the demon Daki.",zh:"許多人被鬼墮姬擄走。",img:"covers/L07_s01.jpg"},
    {en:"The district was protected by four brave slayers.",zh:"花街由四名勇敢的隊士守護。",img:"covers/L07_s02.jpg"},
    {en:"Both heads must be cut at the same time.",zh:"兩顆頭必須同時被斬下。",img:"covers/L07_s03.jpg"},
    {en:"Gyutaro was hidden inside his sister's body.",zh:"妓夫太郎被藏在妹妹的體內。",img:"covers/L07_s04.jpg"},
    {en:"The demons were finally defeated by the team.",zh:"那兩隻鬼最終被隊伍擊敗。",img:"covers/L07_s05.jpg"},
    {en:"Tengen is the Hashira who led the mission.",zh:"天元是領導這次任務的柱。",img:"covers/L07_s06.jpg"},
    {en:"The demon that attacked the city was cruel.",zh:"攻擊城市的那隻鬼很殘忍。",img:"covers/L07_s07.jpg"},
    {en:"Daki used sashes which could crush buildings.",zh:"墮姬使用能粉碎建築的腰帶。",img:"covers/L07_s08.jpg"},
    {en:"Gyutaro was the brother whose hatred made him strong.",zh:"妓夫太郎是那位因憎恨而強大的哥哥。",img:"covers/L07_s09.jpg"},
    {en:"The slayers who never gave up finally won.",zh:"永不放棄的隊士終於獲勝。",img:"covers/L07_s10.jpg"}
  ],
  vocab:[
    {w:"take",pos:"v.",d:"擄走、帶走（過去 took）"},{w:"district",pos:"n.",d:"區、地帶"},
    {w:"sash",pos:"n.",d:"腰帶、布帶"},{w:"hidden",pos:"adj.",d:"隱藏的"},
    {w:"cruel",pos:"adj.",d:"殘忍的"},{w:"crush",pos:"v.",d:"壓碎"},
    {w:"hatred",pos:"n.",d:"憎恨"},{w:"lead",pos:"v.",d:"領導（過去 led）"},
    {w:"behead",pos:"v.",d:"斬首"},{w:"mission",pos:"n.",d:"任務"}
  ],
  grammar:[
    {rule:"<em>被動語態</em>：<b>be + 過去分詞(p.p.)</b>，強調動作承受者，執行者用 <b>by</b>。過去被動 was/were + p.p.；含助動詞用 <b>be</b> 原形：must <b>be</b> cut。"},
    {rule:"<em>關係代名詞</em>：<b>who</b>修飾人、<b>which</b>修飾物、<b>that</b>人物皆可、<b>whose</b>表「…的」。"},
    {rule:"被動 p.p. 不規則：take→taken, hide→hidden, cut→cut, defeat→defeated。"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"Many people ____ by Daki. (take, 過去被動)",opts:["were taken","took","are taking","take"],a:0,ex:"被動 were + p.p. taken。"},
    {cat:"g",t:"選擇題",q:"Both heads ____ at the same time. (cut, must 被動)",opts:["must be cut","must cut","must cutting","must cuts"],a:0,ex:"must + be + p.p. cut。"},
    {cat:"g",t:"填空題",q:"Gyutaro ____ (hide) inside her body. (過去被動)",opts:["was hidden","hid","is hiding","hides"],a:0,ex:"被動 was hidden。"},
    {cat:"g",t:"是非題",q:"\"The demons were defeated by the team.\" 是被動語態。",opts:["正確 True","錯誤 False"],a:0,ex:"were + p.p.，正確。"},
    {cat:"g",t:"選擇題",q:"Tengen is the Hashira ____ led the mission.",opts:["which","who","whose","where"],a:1,ex:"修飾人 → who。"},
    {cat:"g",t:"選擇題",q:"Daki used sashes ____ could crush buildings.",opts:["who","which","whose","when"],a:1,ex:"修飾物 → which。"},
    {cat:"g",t:"填空題",q:"Gyutaro was the brother ____ hatred made him strong.",opts:["whose","who","which","that"],a:0,ex:"表「他的憎恨」用 whose。"},
    {cat:"g",t:"是非題",q:"\"The demon which attacked people was cruel.\" 文法正確。",opts:["正確 True","錯誤 False"],a:0,ex:"that/which 修飾物/動物皆可，正確。"},
    {cat:"v",t:"選擇題",q:"\"district\" 的意思是？",opts:["區、地帶","距離","醫生","地震"],a:0,ex:"district = 區、地帶。"},
    {cat:"v",t:"選擇題",q:"\"cruel\" 的中文是？",opts:["殘忍的","可愛的","好奇的","清脆的"],a:0,ex:"cruel = 殘忍的。"},
    {cat:"v",t:"選擇題",q:"\"crush\" 的意思是？",opts:["壓碎","沖洗","現金","人群"],a:0,ex:"crush = 壓碎。"},
    {cat:"v",t:"選擇題",q:"\"hatred\" 的意思是？",opts:["憎恨","習慣","帽子","硬度"],a:0,ex:"hatred = 憎恨。"},
    {cat:"v",t:"選擇題",q:"The past form of \"lead\" is ____.",opts:["leaded","led","leded","leads"],a:1,ex:"lead→led。"},
    {cat:"v",t:"是非題",q:"\"hidden\" 是 hide 的過去分詞。",opts:["正確 True","錯誤 False"],a:0,ex:"hide→hid→hidden，True。"},
    {cat:"v",t:"選擇題",q:"\"behead\" 的意思最接近？",opts:["斬首","領先","治癒","加熱"],a:0,ex:"behead = 斬首。"},
    {cat:"r",t:"選擇題",q:"Who were the two demons of Upper Six?",opts:["Daki and Gyutaro","Rui and Enmu","Akaza and Doma","Tengen and Tanjiro"],a:0,ex:"Daki... and her brother Gyutaro。"},
    {cat:"r",t:"選擇題",q:"Where was Gyutaro hidden?",opts:["In a cave","Inside his sister's body","On the train","Under the ground"],a:1,ex:"hidden inside her body。"},
    {cat:"r",t:"選擇題",q:"What was the secret to defeating them?",opts:["Use fire","Cut both heads at the same time","Wait for rain","Run away"],a:1,ex:"both demon heads had to be cut at the same time。"},
    {cat:"r",t:"選擇題",q:"Who led the mission?",opts:["Tanjiro","Tengen Uzui, the Sound Hashira","Giyu","Rengoku"],a:1,ex:"The Sound Hashira, Tengen Uzui, led the mission。"},
    {cat:"r",t:"是非題",q:"花街最終得救了。",opts:["正確 True","錯誤 False"],a:0,ex:"the district was saved at last，True。"},
    {cat:"r",t:"是非題",q:"墮姬與妓夫太郎臨死前毫無人類記憶。",opts:["正確 True","錯誤 False"],a:1,ex:"remembered their sad human past，故 False。"}
  ]
},
/* ===== 8 上弦之伍 玉壺 ===== */ {
  emoji:"🏺", rank:"對等·從屬連接詞", cover:"covers/cover08.jpg",
  title:"上弦之伍・玉壺 Gyokko",
  focus:"文法焦點：對等連接詞 + 從屬連接詞",
  reading:{title:"The Demon in the Pot",
    en:"Gyokko, the Upper Rank Five, attacked the Swordsmith Village, a hidden place where the slayers' special blades were made. Gyokko was strange and cruel, but he was also very powerful. He could hide inside a pot or travel through water, so he was hard to catch. The village was usually quiet, so the sudden attack shocked everyone. Muichiro Tokito, the young Mist Hashira, did not fear him, although Gyokko was an Upper Moon. Because the swordsmiths were in great danger, Muichiro rushed to protect them. When the battle began, the demon laughed, but the young Hashira fought with cold focus. Even though Muichiro was tired, he never stopped. In the end, the village survived because the slayers refused to give up, and the swordsmiths could keep making their blades.",
    zh:"上弦之伍玉壺攻擊了刀匠之里——一個隱密之處，隊士的特殊刀就在那裡打造。玉壺古怪又殘忍，卻也非常強大。他能躲進壺中、穿水而行，因此難以捕捉。村子平時寧靜，這突如其來的攻擊嚇壞了所有人。年輕的霞柱時透無一郎並不怕他，儘管玉壺是上弦之鬼。因為刀匠們身陷危險，無一郎趕去保護他們。戰鬥開始時，那隻鬼大笑，但年輕的柱以冷靜的專注應戰。即使疲憊，無一郎也從未停下。最後村子得以倖存，因為隊士拒絕放棄，刀匠們也能繼續打造刀刃。"},
  sentences:[
    {en:"Gyokko was strange and cruel, but he was powerful.",zh:"玉壺古怪又殘忍，但他很強大。",img:"covers/L08_s01.jpg"},
    {en:"He could hide in a pot or travel through water.",zh:"他能躲進壺中或穿水而行。",img:"covers/L08_s02.jpg"},
    {en:"The village was quiet, so the attack shocked everyone.",zh:"村子很安靜，所以攻擊嚇壞了大家。",img:"covers/L08_s03.jpg"},
    {en:"Muichiro was young, and he fought without fear.",zh:"無一郎很年輕，而且毫無懼色地戰鬥。",img:"covers/L08_s04.jpg"},
    {en:"The demon could win, or he could fall to the blade.",zh:"那隻鬼可能獲勝，也可能死於刀下。",img:"covers/L08_s05.jpg"},
    {en:"Although Gyokko was an Upper Moon, Muichiro was not afraid.",zh:"儘管玉壺是上弦，無一郎並不害怕。",img:"covers/L08_s06.jpg"},
    {en:"Because the smiths were in danger, Muichiro rushed to help.",zh:"因為刀匠們身陷危險，無一郎趕去幫忙。",img:"covers/L08_s07.jpg"},
    {en:"When the demon attacked, the smiths ran for safety.",zh:"當那隻鬼攻擊時，刀匠們逃向安全處。",img:"covers/L08_s08.jpg"},
    {en:"Muichiro kept fighting even though he was tired.",zh:"即使疲憊，無一郎仍持續戰鬥。",img:"covers/L08_s09.jpg"},
    {en:"The village survived because the slayers never gave up.",zh:"村子倖存，因為隊士從未放棄。",img:"covers/L08_s10.jpg"}
  ],
  vocab:[
    {w:"strange",pos:"adj.",d:"奇怪的"},{w:"cruel",pos:"adj.",d:"殘忍的"},
    {w:"pot",pos:"n.",d:"壺、罐"},{w:"shock",pos:"v.",d:"使震驚"},
    {w:"danger",pos:"n.",d:"危險"},{w:"rush",pos:"v.",d:"趕、衝"},
    {w:"safety",pos:"n.",d:"安全"},{w:"focus",pos:"n.",d:"專注"},
    {w:"survive",pos:"v.",d:"倖存"},{w:"blade",pos:"n.",d:"刀刃"}
  ],
  grammar:[
    {rule:"<em>對等連接詞</em>：<b>and</b>(並列)、<b>but</b>(轉折)、<b>or</b>(選擇)、<b>so</b>(結果)，連接對等的字/句。"},
    {rule:"<em>從屬連接詞</em>：<b>because</b>(因為)、<b>although/even though</b>(雖然/即使)、<b>when</b>(當…時)，引導附屬子句。"},
    {rule:"注意：although 與 but 不可並用；because(原因) 與 so(結果) 方向相反，勿混。"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"Gyokko was strange ____ cruel. (並列)",opts:["and","but","or","because"],a:0,ex:"並列用 and。"},
    {cat:"g",t:"選擇題",q:"The village was quiet, ____ the attack shocked all. (結果)",opts:["and","but","so","although"],a:2,ex:"結果用 so。"},
    {cat:"g",t:"填空題",q:"He could hide in a pot ____ travel through water. (選擇)",opts:["or","and","but","because"],a:0,ex:"選擇用 or。"},
    {cat:"g",t:"是非題",q:"\"He was strong but slow.\" 文法正確。",opts:["正確 True","錯誤 False"],a:0,ex:"but 連接對比，正確。"},
    {cat:"g",t:"選擇題",q:"____ Gyokko was an Upper Moon, Muichiro was not afraid. (雖然)",opts:["Although","Because","So","And"],a:0,ex:"讓步用 Although。"},
    {cat:"g",t:"選擇題",q:"____ the smiths were in danger, Muichiro rushed to help. (因為)",opts:["Because","Although","So","But"],a:0,ex:"原因用 Because。"},
    {cat:"g",t:"填空題",q:"____ the demon attacked, the smiths ran. (當…時)",opts:["When","Because","Although","So"],a:0,ex:"時間用 When。"},
    {cat:"g",t:"是非題",q:"\"Although he was tired, but he kept fighting.\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"although 與 but 不可並用，故 False。"},
    {cat:"v",t:"選擇題",q:"\"strange\" 的意思是？",opts:["奇怪的","強壯的","筆直的","陌生人"],a:0,ex:"strange = 奇怪的。"},
    {cat:"v",t:"選擇題",q:"\"shock\" (動詞) 的意思是？",opts:["使震驚","購物","關閉","縮短"],a:0,ex:"shock = 使震驚。"},
    {cat:"v",t:"選擇題",q:"\"rush\" 的中文是？",opts:["趕、衝","生鏽","壓碎","休息"],a:0,ex:"rush = 趕、衝。"},
    {cat:"v",t:"選擇題",q:"\"safety\" 的意思是？",opts:["安全","軟體","士兵","季節"],a:0,ex:"safety = 安全。"},
    {cat:"v",t:"選擇題",q:"\"focus\" (名詞) 的意思最接近？",opts:["專注","食物","力量","恐懼"],a:0,ex:"focus = 專注。"},
    {cat:"v",t:"是非題",q:"\"danger\" 的意思是「安全」。",opts:["正確 True","錯誤 False"],a:1,ex:"danger = 危險，故 False。"},
    {cat:"v",t:"選擇題",q:"\"blade\" 的中文是？",opts:["刀刃","葉片","責備","遊戲"],a:0,ex:"blade = 刀刃（也可指葉片）。"},
    {cat:"r",t:"選擇題",q:"What is the Swordsmith Village?",opts:["A market","A hidden place where blades are made","A school","A prison"],a:1,ex:"a hidden place where the slayers' special blades were made。"},
    {cat:"r",t:"選擇題",q:"How could Gyokko move around?",opts:["By flying","By hiding in a pot or traveling through water","By train","By digging"],a:1,ex:"hide inside a pot or travel through water。"},
    {cat:"r",t:"選擇題",q:"Who fought Gyokko?",opts:["Muichiro, the Mist Hashira","Rengoku","Tengen","Shinobu"],a:0,ex:"Muichiro Tokito, the young Mist Hashira。"},
    {cat:"r",t:"選擇題",q:"Why did the village survive?",opts:["The demon left","The slayers refused to give up","It rained","Muzan helped"],a:1,ex:"the slayers refused to give up。"},
    {cat:"r",t:"是非題",q:"刀匠之里平時很寧靜。",opts:["正確 True","錯誤 False"],a:0,ex:"The village was usually quiet，True。"},
    {cat:"r",t:"是非題",q:"無一郎因為害怕而逃跑了。",opts:["正確 True","錯誤 False"],a:1,ex:"did not fear him... never stopped，故 False。"}
  ]
},
/* ===== 9 上弦之肆 半天狗 ===== */ {
  emoji:"😈", rank:"條件句·附加問句", cover:"covers/cover09.jpg",
  title:"上弦之肆・半天狗 Hantengu",
  focus:"文法焦點：第一類條件句 (if) + 附加問句 (tag questions)",
  reading:{title:"The Demon Who Splits",
    en:"Hantengu, the Upper Rank Four, also attacked the Swordsmith Village. He was a strange enemy, because he could split into many bodies. Each body showed a different feeling, such as anger or sorrow. If the slayers cut a clone, it would only multiply, so attacking the clones was useless. The real Hantengu was tiny and hid in fear. Tanjiro understood the trick: \"If we find the real body, we will win.\" Nezuko, Genya, and the Love Hashira Mitsuri all joined the fight. \"If we work together, we will protect the village,\" Tanjiro said. The battle lasted until morning. \"The sun is rising, isn't it?\" someone shouted. When the bright light touched the demon, it could no longer escape, and the long, hard fight finally came to an end.",
    zh:"上弦之肆半天狗也攻擊了刀匠之里。他是個奇特的敵人，因為他能分裂成許多分身，每個分身表現出不同情緒，例如憤怒或悲傷。如果隊士砍掉一個分身，它只會不斷增生，所以攻擊分身毫無用處。真正的半天狗很小，藏在恐懼之中。炭治郎看穿詭計：「只要找到本體，我們就能贏。」禰豆子、玄彌與戀柱蜜璃都加入戰鬥。「只要齊心協力，我們就能守護村子，」炭治郎說。戰鬥持續到清晨。「太陽升起來了，不是嗎？」有人大喊。當明亮的陽光照到那隻鬼，它再也無法逃脫，這場漫長艱苦的戰鬥終於落幕。"},
  sentences:[
    {en:"If we find the real body, we will win.",zh:"只要找到本體，我們就會贏。",img:"covers/L09_s01.jpg"},
    {en:"If you cut a clone, it will only multiply.",zh:"如果你砍一個分身，它只會增生。",img:"covers/L09_s02.jpg"},
    {en:"The demon will escape if the sun does not rise.",zh:"如果太陽不升起，那隻鬼就會逃走。",img:"covers/L09_s03.jpg"},
    {en:"If Nezuko helps us, we will have a chance.",zh:"如果禰豆子幫我們，我們就有機會。",img:"covers/L09_s04.jpg"},
    {en:"If we work together, we will protect the village.",zh:"只要齊心協力，我們就能守護村子。",img:"covers/L09_s05.jpg"},
    {en:"Hantengu is hard to kill, isn't he?",zh:"半天狗很難殺死，不是嗎？",img:"covers/L09_s06.jpg"},
    {en:"We can find the real body, can't we?",zh:"我們能找到本體，不是嗎？",img:"covers/L09_s07.jpg"},
    {en:"You won't give up, will you?",zh:"你不會放棄，會嗎？",img:"covers/L09_s08.jpg"},
    {en:"Mitsuri is very strong, isn't she?",zh:"蜜璃非常強，不是嗎？",img:"covers/L09_s09.jpg"},
    {en:"They fought bravely until dawn, didn't they?",zh:"他們奮戰到黎明，不是嗎？",img:"covers/L09_s10.jpg"}
  ],
  vocab:[
    {w:"split",pos:"v.",d:"分裂"},{w:"body",pos:"n.",d:"身體、本體"},
    {w:"clone",pos:"n.",d:"分身、複製體"},{w:"multiply",pos:"v.",d:"增生、繁殖"},
    {w:"feeling",pos:"n.",d:"情緒、感覺"},{w:"escape",pos:"v.",d:"逃脫"},
    {w:"chance",pos:"n.",d:"機會"},{w:"dawn",pos:"n.",d:"黎明"},
    {w:"trick",pos:"n.",d:"詭計、把戲"},{w:"protect",pos:"v.",d:"保護"}
  ],
  grammar:[
    {rule:"<em>第一類條件句</em>(可能成真)：<b>If + 現在式, 主詞 + will + 原形</b>。if 子句用<b>現在式</b>，不可用 will。"},
    {rule:"<em>附加問句</em>：前肯定→後否定、前否定→後肯定；時態/助動詞一致：is→isn't, can→can't, will→won't, did→didn't。"},
    {rule:"順序可對調：We will win <b>if</b> we find it.（對調時通常不加逗號）"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"\"If we find the real body, we ____.\"",opts:["win","will win","won","winning"],a:1,ex:"主句用 will win。"},
    {cat:"g",t:"選擇題",q:"\"If you ____ a clone, it will multiply.\" (cut)",opts:["will cut","cut","cuts","cutting"],a:1,ex:"if 子句用現在式，you→cut。"},
    {cat:"g",t:"填空題",q:"\"The demon will escape if the sun ____ rise.\" (not)",opts:["does not","will not","is not","do not"],a:0,ex:"if 子句現在式否定 does not rise。"},
    {cat:"g",t:"是非題",q:"\"If he will come, we will win.\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"if 子句不可用 will，故 False。"},
    {cat:"g",t:"選擇題",q:"\"Hantengu is hard to kill, ____?\"",opts:["is he","isn't he","does he","won't he"],a:1,ex:"前肯定 is → isn't he。"},
    {cat:"g",t:"選擇題",q:"\"You won't give up, ____?\"",opts:["will you","won't you","do you","did you"],a:0,ex:"前否定 won't → will you。"},
    {cat:"g",t:"填空題",q:"\"They fought bravely, ____?\"",opts:["didn't they","did they","weren't they","don't they"],a:0,ex:"前肯定過去式 → didn't they。"},
    {cat:"g",t:"是非題",q:"\"Mitsuri is strong, is she?\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"前肯定應接否定 isn't she，故 False。"},
    {cat:"v",t:"選擇題",q:"\"split\" 的意思是？",opts:["分裂","噴灑","運動","抱怨"],a:0,ex:"split = 分裂。"},
    {cat:"v",t:"選擇題",q:"\"clone\" 在此指？",opts:["分身、複製體","小丑","雲","線索"],a:0,ex:"clone = 分身、複製體。"},
    {cat:"v",t:"選擇題",q:"\"multiply\" 的意思是？",opts:["增生、繁殖","減少","乘車","靜音"],a:0,ex:"multiply = 增生、繁殖。"},
    {cat:"v",t:"選擇題",q:"\"dawn\" 的中文是？",opts:["黎明","黃昏","草坪","門"],a:0,ex:"dawn = 黎明。"},
    {cat:"v",t:"選擇題",q:"\"trick\" 的意思最接近？",opts:["詭計、把戲","卡車","軌道","厚的"],a:0,ex:"trick = 詭計、把戲。"},
    {cat:"v",t:"是非題",q:"\"chance\" 可指「機會」。",opts:["正確 True","錯誤 False"],a:0,ex:"chance = 機會，True。"},
    {cat:"v",t:"選擇題",q:"\"feeling\" 的中文是？",opts:["情緒、感覺","田野","費用","填滿"],a:0,ex:"feeling = 情緒、感覺。"},
    {cat:"r",t:"選擇題",q:"What special power did Hantengu have?",opts:["Fire breath","He could split into many bodies","Flying","Reading minds"],a:1,ex:"he could split into many bodies。"},
    {cat:"r",t:"選擇題",q:"What happened if a slayer cut a clone?",opts:["It died","It would multiply","It turned human","Nothing"],a:1,ex:"it would only multiply。"},
    {cat:"r",t:"選擇題",q:"What was the key to winning?",opts:["Finding the real body","Cutting every clone","Waiting one week","Using fire"],a:0,ex:"If we find the real body, we will win。"},
    {cat:"r",t:"選擇題",q:"What finally stopped the demon?",opts:["A storm","The rising sun","A trap","A wall"],a:1,ex:"When the bright light touched the demon, it could no longer escape。"},
    {cat:"r",t:"是非題",q:"戀柱蜜璃也加入了這場戰鬥。",opts:["正確 True","錯誤 False"],a:0,ex:"the Love Hashira Mitsuri all joined the fight，True。"},
    {cat:"r",t:"是非題",q:"攻擊半天狗的分身是有效的取勝方法。",opts:["正確 True","錯誤 False"],a:1,ex:"attacking the clones was useless，故 False。"}
  ]
},
/* ===== 10 上弦之參 猗窩座 ===== */ {
  emoji:"👊", rank:"假設語氣·間接問句", cover:"covers/cover10.jpg",
  title:"上弦之參・猗窩座 Akaza",
  focus:"文法焦點：第二類條件句 (假設語氣) + 間接問句",
  reading:{title:"The Demon Who Loved Strength",
    en:"Akaza, the Upper Rank Three, had killed the Flame Hashira Rengoku on the Mugen Train. He loved strong fighters and always invited them to become demons. Tanjiro never forgot that night, and he often wondered why Akaza had thrown away his humanity. \"If I were stronger, I would have saved Rengoku,\" Tanjiro thought sadly. Later, in the Infinity Castle, Tanjiro and Giyu faced Akaza again. \"Do you know how we can break his armor?\" Giyu asked. Nobody knew where Akaza kept his oldest memories, but as the fight went on, the demon began to remember his human past. If Akaza were still human, he would not be so cruel. In the end, those buried memories weakened him, and the two slayers finally defeated the demon who had loved only strength.",
    zh:"上弦之參猗窩座曾在無限列車上殺死炎柱煉獄。他熱愛強者，總邀請他們成為鬼。炭治郎never忘記那一夜，常想著猗窩座為何捨棄了人性。「如果我更強，就能救下煉獄，」炭治郎悲傷地想。後來在無限城，炭治郎與義勇再次面對猗窩座。「你知道我們要怎麼破他的鎧甲嗎？」義勇問。沒有人知道猗窩座把最古老的記憶藏在哪裡，但隨著戰鬥進行，這隻鬼開始想起人類的過往。如果猗窩座still是人，他就不會如此殘忍。最終，那些埋藏的記憶削弱了他，兩名隊士終於打敗了這隻只愛力量的鬼。"},
  sentences:[
    {en:"\"If I were stronger, I would have saved Rengoku.\"",zh:"「如果我更強，就能救下煉獄。」",img:"covers/L10_s01.jpg"},
    {en:"\"If Akaza were human, he would not be so cruel.\"",zh:"「如果猗窩座是人，他就不會如此殘忍。」",img:"covers/L10_s02.jpg"},
    {en:"\"If we had more time, we would heal our wounds.\"",zh:"「如果我們有更多時間，就能治好傷。」",img:"covers/L10_s03.jpg"},
    {en:"\"If I were you, I would never become a demon.\"",zh:"「如果我是你，我絕不會變成鬼。」",img:"covers/L10_s04.jpg"},
    {en:"\"If the sun rose now, the demon would burn.\"",zh:"「如果現在太陽升起，那隻鬼就會燃燒。」",img:"covers/L10_s05.jpg"},
    {en:"Tanjiro wondered why Akaza had become a demon.",zh:"炭治郎想知道猗窩座為何成為鬼。",img:"covers/L10_s06.jpg"},
    {en:"\"Do you know how we can defeat him?\"",zh:"「你知道我們要如何打敗他嗎？」",img:"covers/L10_s07.jpg"},
    {en:"Nobody knew where Akaza kept his memories.",zh:"沒有人知道猗窩座把記憶藏在哪裡。",img:"covers/L10_s08.jpg"},
    {en:"\"Can you tell me what he fears most?\"",zh:"「你能告訴我他最怕什麼嗎？」",img:"covers/L10_s09.jpg"},
    {en:"They asked when the next attack would come.",zh:"他們問下一次攻擊何時會來。",img:"covers/L10_s10.jpg"}
  ],
  vocab:[
    {w:"invite",pos:"v.",d:"邀請"},{w:"humanity",pos:"n.",d:"人性"},
    {w:"heal",pos:"v.",d:"治癒"},{w:"wound",pos:"n.",d:"傷口"},
    {w:"cruel",pos:"adj.",d:"殘忍的"},{w:"armor",pos:"n.",d:"鎧甲"},
    {w:"memory",pos:"n.",d:"記憶"},{w:"buried",pos:"adj.",d:"埋藏的"},
    {w:"weaken",pos:"v.",d:"削弱"},{w:"defeat",pos:"v.",d:"打敗"}
  ],
  grammar:[
    {rule:"<em>第二類條件句</em>(與現在事實相反)：<b>If + 過去式, 主詞 + would + 原形</b>。be 動詞慣用 <b>were</b>：If I <b>were</b> you…。"},
    {rule:"<em>間接問句</em>：把問句放進句中(know/wonder/tell me + 疑問詞…)，用<b>肯定句語序</b>(主詞+動詞)，不倒裝。"},
    {rule:"直接 Where <b>does</b> he live? → 間接 …where he <b>lives</b>. 直接 What <b>is</b> it? → …what it <b>is</b>。"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"\"If I ____ stronger, I would save him.\"",opts:["am","were","will be","be"],a:1,ex:"假設語氣 be 用 were。"},
    {cat:"g",t:"選擇題",q:"\"If Akaza were human, he ____ so cruel.\"",opts:["will not be","would not be","is not","was not"],a:1,ex:"主句 would + 原形 be。"},
    {cat:"g",t:"填空題",q:"\"If we ____ (have) more time, we would heal.\"",opts:["had","have","will have","having"],a:0,ex:"第二類條件 if 用過去式 had。"},
    {cat:"g",t:"是非題",q:"\"If I will be you, I would refuse.\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"if 子句不可用 will，應為 If I were you，故 False。"},
    {cat:"g",t:"選擇題",q:"Tanjiro wondered why Akaza ____ a demon. (become, 間接)",opts:["had become","had he become","did become","become"],a:0,ex:"間接問句用肯定語序 why Akaza had become。"},
    {cat:"g",t:"選擇題",q:"\"Do you know how we ____ defeat him?\"",opts:["can","can we","do","could we"],a:0,ex:"肯定語序 how we can defeat。"},
    {cat:"g",t:"填空題",q:"Nobody knew where Akaza ____ his memories. (keep, 過去)",opts:["kept","did keep","keeps","did he keep"],a:0,ex:"間接問句直接用動詞 kept。"},
    {cat:"g",t:"是非題",q:"\"Can you tell me what does he fear?\" 文法正確。",opts:["正確 True","錯誤 False"],a:1,ex:"間接問句不可倒裝，應為 what he fears，故 False。"},
    {cat:"v",t:"選擇題",q:"\"invite\" 的意思是？",opts:["邀請","發明","投資","隱形"],a:0,ex:"invite = 邀請。"},
    {cat:"v",t:"選擇題",q:"\"humanity\" 在此指？",opts:["人性","濕度","謙虛","幽默"],a:0,ex:"humanity = 人性。"},
    {cat:"v",t:"選擇題",q:"\"heal\" 的中文是？",opts:["治癒","聽見","隱藏","加熱"],a:0,ex:"heal = 治癒。"},
    {cat:"v",t:"選擇題",q:"\"armor\" 的意思是？",opts:["鎧甲","手臂","軍隊","氣味"],a:0,ex:"armor = 鎧甲。"},
    {cat:"v",t:"選擇題",q:"\"weaken\" 的意思是？",opts:["削弱","加強","醒來","編織"],a:0,ex:"weaken = 削弱。"},
    {cat:"v",t:"是非題",q:"\"memory\" 的意思是「記憶」。",opts:["正確 True","錯誤 False"],a:0,ex:"memory = 記憶，True。"},
    {cat:"v",t:"選擇題",q:"\"wound\" (名詞) 的中文是？",opts:["傷口","風","世界","木材"],a:0,ex:"wound = 傷口。"},
    {cat:"r",t:"選擇題",q:"Whom had Akaza killed on the Mugen Train?",opts:["Tanjiro","The Flame Hashira Rengoku","Giyu","Muichiro"],a:1,ex:"had killed the Flame Hashira Rengoku。"},
    {cat:"r",t:"選擇題",q:"What did Akaza love?",opts:["Money","Strong fighters / strength","Food","Sleep"],a:1,ex:"He loved strong fighters。"},
    {cat:"r",t:"選擇題",q:"What weakened Akaza in the end?",opts:["The rain","His buried human memories","A poison","A trap"],a:1,ex:"those buried memories weakened him。"},
    {cat:"r",t:"選擇題",q:"Who fought Akaza in the Infinity Castle?",opts:["Tanjiro and Giyu","Zenitsu alone","Shinobu","Tengen"],a:0,ex:"Tanjiro and Giyu faced Akaza again。"},
    {cat:"r",t:"是非題",q:"猗窩座總是邀請強者成為鬼。",opts:["正確 True","錯誤 False"],a:0,ex:"always invited them to become demons，True。"},
    {cat:"r",t:"是非題",q:"炭治郎早已忘記煉獄之死。",opts:["正確 True","錯誤 False"],a:1,ex:"Tanjiro never forgot that night，故 False。"}
  ]
},
/* ===== 11 上弦之貳 童磨 ===== */ {
  emoji:"❄️", rank:"時態總複習", cover:"covers/cover11.jpg",
  title:"上弦之貳・童磨 Doma",
  focus:"文法綜合複習：一般過去式 + 現在完成式 + 被動語態",
  reading:{title:"The Smiling Demon",
    en:"Doma was the Upper Rank Two and the leader of a false religion. Many lonely people were tricked by his kind smile, and they were eaten in his temple. Doma had never felt real love or sorrow; he only pretended. Shinobu, the Insect Hashira, has hated him for years, because her older sister was killed by this demon long ago. Shinobu was small, so she made a deadly wisteria poison and hid it inside her own body. During the battle, she was absorbed by Doma, but her poison was already working. Her student Kanao and the wild fighter Inosuke have trained hard for this moment. Together they finished what Shinobu had started, and the smiling demon was finally defeated. The victims of his temple have never been forgotten.",
    zh:"童磨是上弦之貳，也是邪教的教主。許多孤獨的人被他親切的笑容欺騙，在他的神殿被吞食。童磨從未感受過真正的愛或悲傷，他只是假裝。蟲柱胡蝶忍多年來一直憎恨他，因為她的姊姊很久以前被這隻鬼殺害。忍身形嬌小，便製作了致命的紫藤毒藏在自己體內。戰鬥中她被童磨吸收，但毒藥早已生效。她的弟子栗花落カナヲ與狂野的伊之助為此刻苦練多時。兩人合力完成了忍未竟之事，這隻微笑的鬼終於被擊敗。神殿那些受害者從未被遺忘。"},
  sentences:[
    {en:"Doma was the Upper Rank Two of the Twelve Kizuki.",zh:"童磨是十二鬼月的上弦之貳。",img:"covers/L11_s01.jpg"},
    {en:"Many lonely people were tricked by his smile.",zh:"許多孤獨的人被他的笑容欺騙。",img:"covers/L11_s02.jpg"},
    {en:"Shinobu has hated Doma for many years.",zh:"忍多年來一直憎恨童磨。",img:"covers/L11_s03.jpg"},
    {en:"Her older sister was killed by this demon.",zh:"她的姊姊被這隻鬼殺害。",img:"covers/L11_s04.jpg"},
    {en:"Shinobu made a deadly poison from wisteria.",zh:"忍用紫藤製作了致命的毒。",img:"covers/L11_s05.jpg"},
    {en:"The poison was hidden inside her own body.",zh:"那毒被藏在她自己體內。",img:"covers/L11_s06.jpg"},
    {en:"Kanao and Inosuke have trained for this battle.",zh:"カナヲ與伊之助為這場戰鬥訓練已久。",img:"covers/L11_s07.jpg"},
    {en:"Doma was finally defeated by the two fighters.",zh:"童磨最終被兩名戰士擊敗。",img:"covers/L11_s08.jpg"},
    {en:"He had never understood human feelings.",zh:"他從未理解人類的情感。",img:"covers/L11_s09.jpg"},
    {en:"The victims have never been forgotten.",zh:"那些受害者從未被遺忘。",img:"covers/L11_s10.jpg"}
  ],
  vocab:[
    {w:"religion",pos:"n.",d:"宗教"},{w:"leader",pos:"n.",d:"領袖、教主"},
    {w:"trick",pos:"v.",d:"欺騙"},{w:"poison",pos:"n.",d:"毒藥"},
    {w:"pretend",pos:"v.",d:"假裝"},{w:"sorrow",pos:"n.",d:"悲傷"},
    {w:"victim",pos:"n.",d:"受害者"},{w:"absorb",pos:"v.",d:"吸收"},
    {w:"deadly",pos:"adj.",d:"致命的"},{w:"forget",pos:"v.",d:"忘記"}
  ],
  grammar:[
    {rule:"<em>一般過去式</em>：過去發生且結束(was, made, killed)。<em>現在完成式</em>：have/has+p.p.，表經驗或影響至今(has hated, have trained)。"},
    {rule:"<em>被動語態</em>：be+p.p.，動作承受者當主詞。過去被動 was/were+p.p.(was killed)；完成被動 have/has been+p.p.(has been forgotten)。"},
    {rule:"判斷：明確過去時間→過去式；強調至今經驗/影響→完成式；主詞「被…」→被動。"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"Many people ____ by his smile. (trick, 過去被動)",opts:["were tricked","tricked","have tricked","trick"],a:0,ex:"被動 were + p.p. tricked。"},
    {cat:"g",t:"選擇題",q:"Shinobu ____ Doma for many years. (hate, 完成式)",opts:["has hated","hated","is hating","hate"],a:0,ex:"for many years → 完成式 has hated。"},
    {cat:"g",t:"填空題",q:"Her sister ____ (kill) by this demon. (過去被動)",opts:["was killed","killed","has killed","kills"],a:0,ex:"被動 was killed。"},
    {cat:"g",t:"是非題",q:"\"Shinobu made a poison.\" 是一般過去式。",opts:["正確 True","錯誤 False"],a:0,ex:"made = make 的過去式，正確。"},
    {cat:"g",t:"選擇題",q:"Kanao and Inosuke ____ for this battle. (train, 完成式)",opts:["have trained","has trained","trained","are training"],a:0,ex:"they → have trained。"},
    {cat:"g",t:"選擇題",q:"Doma ____ by the two fighters. (defeat, 過去被動)",opts:["was defeated","defeated","has defeat","defeats"],a:0,ex:"被動 was defeated。"},
    {cat:"g",t:"填空題",q:"The victims have never ____ (forget). (完成被動)",opts:["been forgotten","forgotten","forget","been forget"],a:0,ex:"have been + p.p. forgotten。"},
    {cat:"g",t:"是非題",q:"\"The poison was hidden in her body.\" 是被動語態。",opts:["正確 True","錯誤 False"],a:0,ex:"was + p.p. hidden，正確。"},
    {cat:"v",t:"選擇題",q:"\"trick\" (動詞) 的意思是？",opts:["欺騙","練習","旅行","堆疊"],a:0,ex:"trick = 欺騙。"},
    {cat:"v",t:"選擇題",q:"\"poison\" 的中文是？",opts:["毒藥","池塘","部分","口袋"],a:0,ex:"poison = 毒藥。"},
    {cat:"v",t:"選擇題",q:"\"pretend\" 的意思是？",opts:["假裝","準備","保護","出席"],a:0,ex:"pretend = 假裝。"},
    {cat:"v",t:"選擇題",q:"\"sorrow\" 的意思最接近？",opts:["悲傷","明天","箭","土壤"],a:0,ex:"sorrow = 悲傷。"},
    {cat:"v",t:"選擇題",q:"\"absorb\" 的意思是？",opts:["吸收","缺席","荒謬","稱讚"],a:0,ex:"absorb = 吸收。"},
    {cat:"v",t:"是非題",q:"\"deadly\" 的意思是「致命的」。",opts:["正確 True","錯誤 False"],a:0,ex:"deadly = 致命的，True。"},
    {cat:"v",t:"選擇題",q:"\"religion\" 的中文是？",opts:["宗教","地區","關係","休息"],a:0,ex:"religion = 宗教。"},
    {cat:"r",t:"選擇題",q:"What was Doma?",opts:["A doctor","The leader of a false religion","A swordsmith","A passenger"],a:1,ex:"the leader of a false religion。"},
    {cat:"r",t:"選擇題",q:"Why did Shinobu hate Doma?",opts:["He stole her sword","Her older sister was killed by him","He was loud","He tricked Tanjiro"],a:1,ex:"her older sister was killed by this demon。"},
    {cat:"r",t:"選擇題",q:"Where did Shinobu hide the poison?",opts:["In a pot","Inside her own body","In a temple","In a sword"],a:1,ex:"hid it inside her own body。"},
    {cat:"r",t:"選擇題",q:"Who finally defeated Doma?",opts:["Shinobu alone","Kanao and Inosuke","Tanjiro","Giyu"],a:1,ex:"her student Kanao and... Inosuke... finished it。"},
    {cat:"r",t:"是非題",q:"童磨從未感受過真正的愛或悲傷。",opts:["正確 True","錯誤 False"],a:0,ex:"had never felt real love or sorrow，True。"},
    {cat:"r",t:"是非題",q:"忍的毒藥在戰鬥中完全沒有作用。",opts:["正確 True","錯誤 False"],a:1,ex:"her poison was already working，故 False。"}
  ]
},
/* ===== 12 上弦之壹 黑死牟 ===== */ {
  emoji:"🌙", rank:"子句總複習", cover:"covers/cover12.jpg",
  title:"上弦之壹・黑死牟 Kokushibo",
  focus:"文法綜合複習：關係子句 + 連接詞 + 條件句",
  reading:{title:"The Oldest Blade",
    en:"Kokushibo, the Upper Rank One, was the warrior who had lived for hundreds of years. Long ago he was a human swordsman, but he chose to become a demon because he feared death and wanted more time. The sword which he carried was made from his own body, so it was almost unbreakable. Although he was incredibly strong, four slayers fought him together. Gyomei, whose strength was the greatest among the Hashira, led the attack. \"If we attack as one, we will break his guard,\" he said. The young Muichiro and the brothers Sanemi and Genya never retreated, even though they were badly wounded. The battle was the hardest they had ever known. In the end, the demon that had feared death for so long finally fell when the morning light appeared.",
    zh:"上弦之壹黑死牟是活了數百年的戰士。很久以前他是人類劍士，卻因畏懼死亡、渴望更多時間而選擇成為鬼。他所持的刀由自身軀體所化，幾乎不會斷裂。儘管他強得驚人，四名隊士仍合力與他作戰。在柱之中力量最強的悲鳴嶼率領攻擊。「只要齊心攻擊，我們就能破他的防禦，」他說。年輕的無一郎與不死川兄弟實彌、玄彌從不退縮，即使身受重傷。這是他們經歷過最艱難的一戰。最後，那隻畏懼死亡如此之久的鬼，終於在晨光浮現時倒下。"},
  sentences:[
    {en:"Kokushibo was the warrior who became Upper One.",zh:"黑死牟是成為上弦之壹的戰士。",img:"covers/L12_s01.jpg"},
    {en:"The sword which he carried was almost unbreakable.",zh:"他所持的刀幾乎堅不可摧。",img:"covers/L12_s02.jpg"},
    {en:"He was very old, but his will never weakened.",zh:"他非常年老，但意志從未衰退。",img:"covers/L12_s03.jpg"},
    {en:"Because his power was huge, four slayers fought together.",zh:"因為他力量龐大，四名隊士合力作戰。",img:"covers/L12_s04.jpg"},
    {en:"\"If we attack as one, we will break his guard.\"",zh:"「只要齊心攻擊，就能破他的防禦。」",img:"covers/L12_s05.jpg"},
    {en:"Gyomei, whose strength was greatest, led the attack.",zh:"力量最強的悲鳴嶼率領攻擊。",img:"covers/L12_s06.jpg"},
    {en:"Although they were wounded, they did not retreat.",zh:"儘管身受重傷，他們並未撤退。",img:"covers/L12_s07.jpg"},
    {en:"\"If I were faster, I could land the final blow.\"",zh:"「如果我更快，就能給出致命一擊。」",img:"covers/L12_s08.jpg"},
    {en:"Genya fought hard, so the others gained time.",zh:"玄彌奮力作戰，於是其他人爭取到時間。",img:"covers/L12_s09.jpg"},
    {en:"The demon that feared death finally fell at dawn.",zh:"那隻畏懼死亡的鬼終於在黎明倒下。",img:"covers/L12_s10.jpg"}
  ],
  vocab:[
    {w:"warrior",pos:"n.",d:"戰士"},{w:"weaken",pos:"v.",d:"衰退、削弱"},
    {w:"huge",pos:"adj.",d:"巨大的"},{w:"guard",pos:"n.",d:"防禦、守衛"},
    {w:"wound",pos:"v.",d:"使受傷"},{w:"strength",pos:"n.",d:"力量"},
    {w:"retreat",pos:"v.",d:"撤退"},{w:"ancient",pos:"adj.",d:"古老的"},
    {w:"blow",pos:"n.",d:"一擊、打擊"},{w:"fall",pos:"v.",d:"倒下（過去 fell）"}
  ],
  grammar:[
    {rule:"<em>關係子句</em>：who(人)、which(物)、that(皆可)、whose(…的)，用來修飾名詞。"},
    {rule:"<em>連接詞</em>：對等 and/but/or/so；從屬 because/although/when。although 不與 but 並用。"},
    {rule:"<em>條件句</em>：第一類 If+現在式, will(可能成真)；第二類 If+過去式, would(與現實相反)。"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"Kokushibo was the warrior ____ became Upper One.",opts:["which","who","whose","when"],a:1,ex:"修飾人 → who。"},
    {cat:"g",t:"選擇題",q:"The sword ____ he carried was unbreakable.",opts:["who","which","whose","where"],a:1,ex:"修飾物 → which。"},
    {cat:"g",t:"選擇題",q:"Gyomei, ____ strength was greatest, led them. (…的)",opts:["who","which","whose","that"],a:2,ex:"表「他的力量」用 whose。"},
    {cat:"g",t:"選擇題",q:"____ his power was huge, four slayers fought him. (因為)",opts:["Because","Although","So","But"],a:0,ex:"原因用 Because。"},
    {cat:"g",t:"選擇題",q:"____ they were wounded, they did not retreat. (儘管)",opts:["Although","Because","So","And"],a:0,ex:"讓步用 Although。"},
    {cat:"g",t:"填空題",q:"\"If we attack as one, we ____ his guard.\" (break, 第一類)",opts:["will break","break","broke","would break"],a:0,ex:"第一類主句 will break。"},
    {cat:"g",t:"選擇題",q:"\"If I ____ faster, I could land the blow.\" (第二類)",opts:["am","were","will be","be"],a:1,ex:"假設語氣 be 用 were。"},
    {cat:"g",t:"是非題",q:"\"Genya fought hard, so they gained time.\" 句意合理。",opts:["正確 True","錯誤 False"],a:0,ex:"so 表結果，合理。"},
    {cat:"v",t:"選擇題",q:"\"warrior\" 的意思是？",opts:["戰士","農夫","商人","水手"],a:0,ex:"warrior = 戰士。"},
    {cat:"v",t:"選擇題",q:"\"huge\" 的中文是？",opts:["巨大的","潮濕的","謙虛的","匆忙的"],a:0,ex:"huge = 巨大的。"},
    {cat:"v",t:"選擇題",q:"\"retreat\" 的意思是？",opts:["撤退","重複","治療","到達"],a:0,ex:"retreat = 撤退。"},
    {cat:"v",t:"選擇題",q:"\"ancient\" 的意思最接近？",opts:["古老的","另一個","生氣的","腳踝"],a:0,ex:"ancient = 古老的。"},
    {cat:"v",t:"選擇題",q:"\"blow\" (名詞) 在此指？",opts:["一擊、打擊","吹風","藍色","綻放"],a:0,ex:"此處 blow = 一擊。"},
    {cat:"v",t:"是非題",q:"\"strength\" 的意思是「力量」。",opts:["正確 True","錯誤 False"],a:0,ex:"strength = 力量，True。"},
    {cat:"v",t:"選擇題",q:"\"guard\" 在此指？",opts:["防禦、守衛","花園","客人","齒輪"],a:0,ex:"此處 guard = 防禦。"},
    {cat:"r",t:"選擇題",q:"Why did Kokushibo become a demon?",opts:["He loved demons","He feared death and wanted more time","He was forced","For money"],a:1,ex:"he feared death and wanted more time。"},
    {cat:"r",t:"選擇題",q:"What was his sword made from?",opts:["Iron","His own body","Wood","Stone"],a:1,ex:"made from his own body。"},
    {cat:"r",t:"選擇題",q:"Who led the attack against him?",opts:["Tanjiro","Gyomei, the Stone Hashira","Zenitsu","Shinobu"],a:1,ex:"Gyomei... led the attack。"},
    {cat:"r",t:"選擇題",q:"When did the demon finally fall?",opts:["At midnight","When the morning light appeared","Never","At noon"],a:1,ex:"finally fell when the morning light appeared。"},
    {cat:"r",t:"是非題",q:"黑死牟原本是人類劍士。",opts:["正確 True","錯誤 False"],a:0,ex:"Long ago he was a human swordsman，True。"},
    {cat:"r",t:"是非題",q:"隊士們因受傷而撤退了。",opts:["正確 True","錯誤 False"],a:1,ex:"they did not retreat，故 False。"}
  ]
},
/* ===== 13 鬼王 無慘 ===== */ {
  emoji:"👑", rank:"全文法總複習", cover:"covers/cover13.jpg",
  title:"鬼王・鬼舞辻無慘 Muzan Kibutsuji",
  focus:"文法總複習：時態 + 被動 + 子句 + 條件句 + 附加問句",
  reading:{title:"The King and the Dawn",
    en:"Muzan Kibutsuji is the demon king who created every other demon. For more than a thousand years, he has feared only one thing: the sunlight. Long ago, he was an ordinary, sick man who became the first demon. On the final night, the slayers were fighting him while the sky slowly grew lighter. Many brave heroes were killed by Muzan, but the others refused to fall back. \"We must hold him until dawn!\" the Hashira shouted. \"If the sun rises, he will turn to ashes.\" If the slayers had given up, the world would have stayed in darkness forever. At last the morning sun rose over the city, and Muzan could not escape its light. The demon king who had brought a thousand years of fear was finally destroyed. Peace has returned to the world, hasn't it?",
    zh:"鬼舞辻無慘是創造所有其他鬼的鬼王。一千多年來，他只畏懼一件事：陽光。很久以前，他是個平凡的病弱男子，後來成為第一隻鬼。最終之夜，隊士們在天色漸亮時與他奮戰。許多勇敢的英雄被無慘殺害，但其餘的人拒絕退卻。「我們必須拖住他到黎明！」柱們高喊。「只要太陽升起，他就會化為灰燼。」若隊士當時放棄，世界將永遠停留在黑暗。終於，朝陽升上城市，無慘無法逃離陽光。那帶來千年恐懼的鬼王終於被消滅。和平已重返人間，不是嗎？"},
  sentences:[
    {en:"Muzan is the demon king who created all demons.",zh:"無慘是創造所有鬼的鬼王。",img:"covers/L13_s01.jpg"},
    {en:"For a thousand years, he has feared only sunlight.",zh:"一千年來，他只畏懼陽光。",img:"covers/L13_s02.jpg"},
    {en:"Long ago, he was an ordinary, sick man.",zh:"很久以前，他是個平凡的病弱男子。",img:"covers/L13_s03.jpg"},
    {en:"The slayers were fighting him while the sky grew light.",zh:"天色漸亮時，隊士們正與他奮戰。",img:"covers/L13_s04.jpg"},
    {en:"Many brave heroes were killed by Muzan that night.",zh:"那一夜許多勇敢的英雄被無慘殺害。",img:"covers/L13_s05.jpg"},
    {en:"\"We must hold him until dawn,\" the Hashira said.",zh:"「我們必須拖住他到黎明，」柱們說。",img:"covers/L13_s06.jpg"},
    {en:"\"If the sun rises, he will turn to ashes.\"",zh:"「只要太陽升起，他就會化為灰燼。」",img:"covers/L13_s07.jpg"},
    {en:"\"If we gave up now, the world would fall.\"",zh:"「如果我們現在放棄，世界就會淪陷。」",img:"covers/L13_s08.jpg"},
    {en:"At last the sun rose, and Muzan could not escape.",zh:"終於太陽升起，無慘無法逃脫。",img:"covers/L13_s09.jpg"},
    {en:"Peace has returned to the world, hasn't it?",zh:"和平已重返人間，不是嗎？",img:"covers/L13_s10.jpg"}
  ],
  vocab:[
    {w:"create",pos:"v.",d:"創造"},{w:"sunlight",pos:"n.",d:"陽光"},
    {w:"ordinary",pos:"adj.",d:"平凡的"},{w:"ashes",pos:"n.",d:"灰燼"},
    {w:"hero",pos:"n.",d:"英雄"},{w:"hold",pos:"v.",d:"拖住、держ（過去 held）"},
    {w:"dawn",pos:"n.",d:"黎明"},{w:"peace",pos:"n.",d:"和平"},
    {w:"escape",pos:"v.",d:"逃脫"},{w:"destroy",pos:"v.",d:"消滅"}
  ],
  grammar:[
    {rule:"本關綜合複習：<em>時態</em>(現在/過去/進行/完成)、<em>被動</em>(be+p.p.)、<em>關係子句</em>(who/which)、<em>條件句</em>(if)、<em>附加問句</em>。"},
    {rule:"判斷時態看時間標誌；主詞「被…」用被動；句尾確認用附加問句(前肯後否)。"},
    {rule:"第一類 If+現在式, will；第二類 If+過去式, would。"}
  ],
  bank:[
    {cat:"g",t:"選擇題",q:"Muzan is the demon king ____ created all demons.",opts:["which","who","whose","when"],a:1,ex:"修飾人(king) → who。"},
    {cat:"g",t:"選擇題",q:"For a thousand years, he ____ only sunlight. (fear, 完成式)",opts:["has feared","feared","fears","is fearing"],a:0,ex:"For + 時間 → 完成式 has feared。"},
    {cat:"g",t:"選擇題",q:"Many heroes ____ by Muzan. (kill, 過去被動)",opts:["were killed","killed","have killed","kill"],a:0,ex:"被動 were killed。"},
    {cat:"g",t:"填空題",q:"The slayers ____ (fight) while the sky grew light.",opts:["were fighting","fought","have fought","fight"],a:0,ex:"while + 過去進行 were fighting。"},
    {cat:"g",t:"選擇題",q:"\"If the sun rises, he ____ to ashes.\" (第一類)",opts:["turns","will turn","turned","would turn"],a:1,ex:"第一類主句 will turn。"},
    {cat:"g",t:"選擇題",q:"\"If we ____ up now, the world would fall.\" (give, 第二類)",opts:["give","gave","will give","given"],a:1,ex:"第二類 if 用過去式 gave。"},
    {cat:"g",t:"選擇題",q:"\"Peace has returned, ____?\" (附加問句)",opts:["has it","hasn't it","does it","isn't it"],a:1,ex:"has returned(完成式肯定) → hasn't it。"},
    {cat:"g",t:"是非題",q:"\"He was an ordinary man.\" 是一般過去式。",opts:["正確 True","錯誤 False"],a:0,ex:"was = be 的過去式，正確。"},
    {cat:"v",t:"選擇題",q:"\"create\" 的意思是？",opts:["創造","批評","哭泣","跨越"],a:0,ex:"create = 創造。"},
    {cat:"v",t:"選擇題",q:"\"sunlight\" 的中文是？",opts:["陽光","週日","曬傷","向日葵"],a:0,ex:"sunlight = 陽光。"},
    {cat:"v",t:"選擇題",q:"\"ordinary\" 的意思是？",opts:["平凡的","有序的","東方的","原本的"],a:0,ex:"ordinary = 平凡的。"},
    {cat:"v",t:"選擇題",q:"\"ashes\" 的意思是？",opts:["灰燼","盒子","岸邊","斧頭"],a:0,ex:"ashes = 灰燼。"},
    {cat:"v",t:"選擇題",q:"\"peace\" 的中文是？",opts:["和平","碎片","豌豆","山峰"],a:0,ex:"peace = 和平。"},
    {cat:"v",t:"是非題",q:"\"destroy\" 的意思是「建造」。",opts:["正確 True","錯誤 False"],a:1,ex:"destroy = 消滅、摧毀，故 False。"},
    {cat:"v",t:"選擇題",q:"\"hero\" 的複數是 ____.",opts:["heros","heroes","heroies","hero"],a:1,ex:"hero→heroes。"},
    {cat:"r",t:"選擇題",q:"What is Muzan?",opts:["A Hashira","The demon king who created all demons","A human doctor","A passenger"],a:1,ex:"the demon king who created every other demon。"},
    {cat:"r",t:"選擇題",q:"What is the one thing Muzan fears?",opts:["Water","Sunlight","Fire","Noise"],a:1,ex:"he has feared only one thing: the sunlight。"},
    {cat:"r",t:"選擇題",q:"What was the slayers' plan?",opts:["Run away","Hold him until dawn","Make peace","Hide"],a:1,ex:"We must hold him until dawn。"},
    {cat:"r",t:"選擇題",q:"How was Muzan finally destroyed?",opts:["By a poison","By the rising morning sun","By fire","By a single sword"],a:1,ex:"the morning sun rose... could not escape its light。"},
    {cat:"r",t:"是非題",q:"無慘很久以前是個平凡的病弱男子。",opts:["正確 True","錯誤 False"],a:0,ex:"he was an ordinary, sick man，True。"},
    {cat:"r",t:"是非題",q:"若隊士當時放棄，世界仍會迎來和平。",opts:["正確 True","錯誤 False"],a:1,ex:"the world would have stayed in darkness，故 False。"}
  ]
}
];

/* ===== 補充單字：每關再 +10 個（總計 20）===== */
const VOCAB2 = [
 [{w:"serve",pos:"v.",d:"侍奉"},{w:"cover",pos:"v.",d:"覆蓋"},{w:"real",pos:"adj.",d:"真實的"},{w:"false",pos:"adj.",d:"虛假的"},{w:"remember",pos:"v.",d:"記得"},{w:"cry",pos:"v.",d:"哭泣"},{w:"human",pos:"n.",d:"人類"},{w:"deep",pos:"adj.",d:"深的"},{w:"arrive",pos:"v.",d:"到達"},{w:"silent",pos:"adj.",d:"寂靜的"}],
 [{w:"remaining",pos:"adj.",d:"剩下的"},{w:"secret",pos:"adj.",d:"祕密的"},{w:"wait",pos:"v.",d:"等待"},{w:"master",pos:"n.",d:"主子"},{w:"lesson",pos:"n.",d:"教訓"},{w:"weak",pos:"adj.",d:"軟弱的"},{w:"allow",pos:"v.",d:"允許"},{w:"watch",pos:"v.",d:"注視"},{w:"servant",pos:"n.",d:"僕人"},{w:"cruel",pos:"adj.",d:"殘忍的"}],
 [{w:"blood",pos:"n.",d:"血"},{w:"grow",pos:"v.",d:"成長"},{w:"death",pos:"n.",d:"死亡"},{w:"answer",pos:"v.",d:"回答"},{w:"feel",pos:"v.",d:"感覺"},{w:"ready",pos:"adj.",d:"準備好的"},{w:"road",pos:"n.",d:"道路"},{w:"learn",pos:"v.",d:"學習"},{w:"hunt",pos:"v.",d:"狩獵"},{w:"weak",pos:"adj.",d:"軟弱的"}],
 [{w:"decide",pos:"v.",d:"決定"},{w:"break",pos:"v.",d:"打破"},{w:"door",pos:"n.",d:"門"},{w:"moment",pos:"n.",d:"時刻"},{w:"safe",pos:"adj.",d:"安全的"},{w:"quick",pos:"adj.",d:"快速的"},{w:"truth",pos:"n.",d:"真相"},{w:"distance",pos:"n.",d:"距離"},{w:"ancient",pos:"adj.",d:"古老的"},{w:"fall",pos:"v.",d:"倒下"}],
 [{w:"enough",pos:"adj.",d:"足夠的"},{w:"hundred",pos:"n.",d:"一百"},{w:"fail",pos:"v.",d:"失敗"},{w:"prove",pos:"v.",d:"證明"},{w:"respect",pos:"v.",d:"尊敬"},{w:"reward",pos:"n.",d:"獎賞"},{w:"wise",pos:"adj.",d:"明智的"},{w:"duty",pos:"n.",d:"職責"},{w:"blood",pos:"n.",d:"血"},{w:"warrior",pos:"n.",d:"戰士"}],
 [{w:"wake",pos:"v.",d:"醒來"},{w:"power",pos:"n.",d:"力量"},{w:"clever",pos:"adj.",d:"聰明的"},{w:"save",pos:"v.",d:"拯救"},{w:"together",pos:"adv.",d:"一起"},{w:"brave",pos:"adj.",d:"勇敢的"},{w:"control",pos:"v.",d:"控制"},{w:"escape",pos:"v.",d:"逃脫"},{w:"effort",pos:"n.",d:"努力"},{w:"terrible",pos:"adj.",d:"可怕的"}],
 [{w:"beautiful",pos:"adj.",d:"美麗的"},{w:"building",pos:"n.",d:"建築物"},{w:"brother",pos:"n.",d:"兄弟"},{w:"sister",pos:"n.",d:"姊妹"},{w:"past",pos:"n.",d:"過去"},{w:"save",pos:"v.",d:"拯救"},{w:"wound",pos:"n.",d:"傷口"},{w:"team",pos:"n.",d:"隊伍"},{w:"remember",pos:"v.",d:"記得"},{w:"danger",pos:"n.",d:"危險"}],
 [{w:"village",pos:"n.",d:"村莊"},{w:"hide",pos:"v.",d:"躲藏"},{w:"laugh",pos:"v.",d:"大笑"},{w:"tired",pos:"adj.",d:"疲累的"},{w:"young",pos:"adj.",d:"年輕的"},{w:"quiet",pos:"adj.",d:"安靜的"},{w:"attack",pos:"v.",d:"攻擊"},{w:"refuse",pos:"v.",d:"拒絕"},{w:"powerful",pos:"adj.",d:"強大的"},{w:"mist",pos:"n.",d:"霧"}],
 [{w:"real",pos:"adj.",d:"真實的"},{w:"anger",pos:"n.",d:"憤怒"},{w:"sorrow",pos:"n.",d:"悲傷"},{w:"tiny",pos:"adj.",d:"微小的"},{w:"find",pos:"v.",d:"找到"},{w:"win",pos:"v.",d:"獲勝"},{w:"bright",pos:"adj.",d:"明亮的"},{w:"sunlight",pos:"n.",d:"陽光"},{w:"together",pos:"adv.",d:"一起"},{w:"hide",pos:"v.",d:"躲藏"}],
 [{w:"strength",pos:"n.",d:"力量"},{w:"fear",pos:"n.",d:"恐懼"},{w:"refuse",pos:"v.",d:"拒絕"},{w:"human",pos:"n.",d:"人類"},{w:"punch",pos:"n.",d:"一拳"},{w:"past",pos:"n.",d:"過去"},{w:"forget",pos:"v.",d:"忘記"},{w:"break",pos:"v.",d:"打破"},{w:"blow",pos:"n.",d:"一擊"},{w:"regret",pos:"v.",d:"後悔"}],
 [{w:"smile",pos:"n.",d:"微笑"},{w:"cult",pos:"n.",d:"邪教"},{w:"temple",pos:"n.",d:"神殿"},{w:"feeling",pos:"n.",d:"感覺"},{w:"hate",pos:"v.",d:"憎恨"},{w:"sister",pos:"n.",d:"姊妹"},{w:"student",pos:"n.",d:"學生"},{w:"finish",pos:"v.",d:"完成"},{w:"remember",pos:"v.",d:"記得"},{w:"empty",pos:"adj.",d:"空的"}],
 [{w:"human",pos:"n.",d:"人類"},{w:"choose",pos:"v.",d:"選擇"},{w:"will",pos:"n.",d:"意志"},{w:"greatest",pos:"adj.",d:"最偉大的"},{w:"tired",pos:"adj.",d:"疲累的"},{w:"dawn",pos:"n.",d:"黎明"},{w:"shape",pos:"n.",d:"形狀"},{w:"brother",pos:"n.",d:"兄弟"},{w:"endless",pos:"adj.",d:"無盡的"},{w:"blade",pos:"n.",d:"刀刃"}],
 [{w:"king",pos:"n.",d:"國王"},{w:"fear",pos:"v.",d:"畏懼"},{w:"sick",pos:"adj.",d:"生病的"},{w:"rise",pos:"v.",d:"升起"},{w:"light",pos:"n.",d:"光"},{w:"brave",pos:"adj.",d:"勇敢的"},{w:"refuse",pos:"v.",d:"拒絕"},{w:"return",pos:"v.",d:"返回"},{w:"forever",pos:"adv.",d:"永遠"},{w:"victory",pos:"n.",d:"勝利"}]
];
VOCAB2.forEach(function(arr,i){ if(LEVELS[i]) LEVELS[i].vocab = LEVELS[i].vocab.concat(arr); });

/* ===== 補充單字題：每關再 +8 題（單字題總計 15，抽 10）===== */
const VQ2 = [
 [ {t:"選擇題",q:"\"serve\" 的意思是？",opts:["侍奉","切開","保留","觀察"],a:0,ex:"serve = 侍奉。"},
   {t:"選擇題",q:"\"real\" 的相反詞是？",opts:["false","deep","silent","human"],a:0,ex:"real(真)↔false(假)。"},
   {t:"選擇題",q:"\"remember\" 的相反詞是？",opts:["forget","cover","cry","arrive"],a:0,ex:"remember(記得)↔forget(忘記)。"},
   {t:"選擇題",q:"\"human\" 的中文是？",opts:["人類","惡魔","英雄","僕人"],a:0,ex:"human = 人類。"},
   {t:"選擇題",q:"\"silent\" 的意思是？",opts:["寂靜的","深的","真實的","虛假的"],a:0,ex:"silent = 寂靜的。"},
   {t:"選擇題",q:"\"arrive\" 的意思是？",opts:["到達","離開","覆蓋","哭泣"],a:0,ex:"arrive = 到達。"},
   {t:"是非題",q:"\"cry\" 的意思是「哭泣」。",opts:["正確 True","錯誤 False"],a:0,ex:"cry = 哭泣，True。"},
   {t:"選擇題",q:"\"deep\" 的中文是？",opts:["深的","淺的","高的","寬的"],a:0,ex:"deep = 深的。"} ],
 [ {t:"選擇題",q:"\"secret\" 的意思是？",opts:["祕密的","剩下的","殘忍的","軟弱的"],a:0,ex:"secret = 祕密的。"},
   {t:"選擇題",q:"\"weak\" 的相反詞是？",opts:["strong","secret","cruel","remaining"],a:0,ex:"weak(弱)↔strong(強)。"},
   {t:"選擇題",q:"\"allow\" 的意思是？",opts:["允許","禁止","等待","注視"],a:0,ex:"allow = 允許。"},
   {t:"選擇題",q:"\"servant\" 的中文是？",opts:["僕人","主人","士兵","客人"],a:0,ex:"servant = 僕人。"},
   {t:"選擇題",q:"\"lesson\" 在此的意思最接近？",opts:["教訓","課本","距離","休息"],a:0,ex:"lesson = 教訓、一課。"},
   {t:"選擇題",q:"\"wait\" 的意思是？",opts:["等待","重量","浪費","走路"],a:0,ex:"wait = 等待。"},
   {t:"是非題",q:"\"cruel\" 的意思是「善良的」。",opts:["正確 True","錯誤 False"],a:1,ex:"cruel = 殘忍的，故 False。"},
   {t:"選擇題",q:"\"master\" 在此指？",opts:["主子","碩士","傑作","僕人"],a:0,ex:"此處 master = 主子。"} ],
 [ {t:"選擇題",q:"\"blood\" 的中文是？",opts:["血","汗","淚","花"],a:0,ex:"blood = 血。"},
   {t:"選擇題",q:"\"death\" 的相反詞是？",opts:["life","road","blood","fear"],a:0,ex:"death(死)↔life(生)。"},
   {t:"選擇題",q:"\"answer\" 的意思是？",opts:["回答","詢問","忘記","狩獵"],a:0,ex:"answer = 回答。"},
   {t:"選擇題",q:"\"ready\" 的意思是？",opts:["準備好的","疲累的","危險的","真實的"],a:0,ex:"ready = 準備好的。"},
   {t:"選擇題",q:"\"road\" 的中文是？",opts:["道路","河流","房間","規則"],a:0,ex:"road = 道路。"},
   {t:"選擇題",q:"\"learn\" 的意思是？",opts:["學習","教導","賺取","傾聽"],a:0,ex:"learn = 學習。"},
   {t:"選擇題",q:"\"hunt\" 的意思最接近？",opts:["狩獵","躲藏","受傷","趕路"],a:0,ex:"hunt = 狩獵。"},
   {t:"是非題",q:"\"grow\" 的意思是「成長」。",opts:["正確 True","錯誤 False"],a:0,ex:"grow = 成長，True。"} ],
 [ {t:"選擇題",q:"\"decide\" 的意思是？",opts:["決定","裝飾","拒絕","下降"],a:0,ex:"decide = 決定。"},
   {t:"選擇題",q:"\"safe\" 的相反詞是？",opts:["dangerous","quick","ancient","deep"],a:0,ex:"safe(安全)↔dangerous(危險)。"},
   {t:"選擇題",q:"\"truth\" 的中文是？",opts:["真相","信任","嘗試","青春"],a:0,ex:"truth = 真相。"},
   {t:"選擇題",q:"\"distance\" 的意思是？",opts:["距離","區域","差異","歷史"],a:0,ex:"distance = 距離。"},
   {t:"選擇題",q:"\"ancient\" 的意思是？",opts:["古老的","足夠的","匆忙的","另一個"],a:0,ex:"ancient = 古老的。"},
   {t:"選擇題",q:"\"quick\" 的相反詞是？",opts:["slow","safe","quiet","huge"],a:0,ex:"quick(快)↔slow(慢)。"},
   {t:"選擇題",q:"\"moment\" 的意思是？",opts:["時刻","母親","金錢","怪物"],a:0,ex:"moment = 時刻。"},
   {t:"是非題",q:"\"door\" 的意思是「門」。",opts:["正確 True","錯誤 False"],a:0,ex:"door = 門，True。"} ],
 [ {t:"選擇題",q:"\"fail\" 的相反詞是？",opts:["succeed","prove","respect","reward"],a:0,ex:"fail(失敗)↔succeed(成功)。"},
   {t:"選擇題",q:"\"prove\" 的意思是？",opts:["證明","移動","推動","給予"],a:0,ex:"prove = 證明。"},
   {t:"選擇題",q:"\"respect\" 的意思是？",opts:["尊敬","期待","休息","檢查"],a:0,ex:"respect = 尊敬。"},
   {t:"選擇題",q:"\"wise\" 的意思是？",opts:["明智的","寬的","狂野的","潮濕的"],a:0,ex:"wise = 明智的。"},
   {t:"選擇題",q:"\"duty\" 的中文是？",opts:["職責","灰塵","一天","懷疑"],a:0,ex:"duty = 職責。"},
   {t:"選擇題",q:"\"reward\" 的意思最接近？",opts:["獎賞","警告","記錄","道路"],a:0,ex:"reward = 獎賞。"},
   {t:"選擇題",q:"\"enough\" 的意思是？",opts:["足夠的","粗糙的","空的","昂貴的"],a:0,ex:"enough = 足夠的。"},
   {t:"是非題",q:"\"hundred\" 的意思是「一千」。",opts:["正確 True","錯誤 False"],a:1,ex:"hundred = 一百，故 False。"} ],
 [ {t:"選擇題",q:"\"wake\" 的相反詞是？",opts:["sleep","save","escape","control"],a:0,ex:"wake(醒)↔sleep(睡)。"},
   {t:"選擇題",q:"\"clever\" 的意思是？",opts:["聰明的","勇敢的","疲累的","可怕的"],a:0,ex:"clever = 聰明的。"},
   {t:"選擇題",q:"\"effort\" 的意思是？",opts:["努力","影響","出口","入口"],a:0,ex:"effort = 努力。"},
   {t:"選擇題",q:"\"brave\" 的意思是？",opts:["勇敢的","膽小的","安靜的","強壯的"],a:0,ex:"brave = 勇敢的。"},
   {t:"選擇題",q:"\"escape\" 的中文是？",opts:["逃脫","景色","昂貴","延伸"],a:0,ex:"escape = 逃脫。"},
   {t:"選擇題",q:"\"save\" 在此的意思是？",opts:["拯救","儲存","節省","以上皆可"],a:2,ex:"save 多義，此故事多指拯救；此題泛指皆可，選最廣義。"},
   {t:"選擇題",q:"\"terrible\" 的意思是？",opts:["可怕的","美好的","普通的","安靜的"],a:0,ex:"terrible = 可怕的。"},
   {t:"是非題",q:"\"power\" 的意思是「力量」。",opts:["正確 True","錯誤 False"],a:0,ex:"power = 力量，True。"} ],
 [ {t:"選擇題",q:"\"beautiful\" 的相反詞是？",opts:["ugly","building","past","team"],a:0,ex:"beautiful(美)↔ugly(醜)。"},
   {t:"選擇題",q:"\"building\" 的中文是？",opts:["建築物","積木","帳單","公車"],a:0,ex:"building = 建築物。"},
   {t:"選擇題",q:"\"wound\" (名詞) 的意思是？",opts:["傷口","風","世界","字詞"],a:0,ex:"wound = 傷口。"},
   {t:"選擇題",q:"\"team\" 的意思是？",opts:["隊伍","茶","淚水","主題"],a:0,ex:"team = 隊伍。"},
   {t:"選擇題",q:"\"past\" 在此的意思是？",opts:["過去","經過","快速","貼上"],a:0,ex:"此處 past = 過去。"},
   {t:"選擇題",q:"\"danger\" 的意思是？",opts:["危險","舞者","女兒","晚餐"],a:0,ex:"danger = 危險。"},
   {t:"選擇題",q:"\"brother\" 與 \"sister\" 分別是？",opts:["兄弟／姊妹","父親／母親","叔叔／阿姨","兒子／女兒"],a:0,ex:"brother 兄弟、sister 姊妹。"},
   {t:"是非題",q:"\"save\" 可以指「拯救」。",opts:["正確 True","錯誤 False"],a:0,ex:"save = 拯救（也可指儲存），True。"} ],
 [ {t:"選擇題",q:"\"hide\" 的相反詞最接近？",opts:["find","laugh","refuse","attack"],a:0,ex:"hide(躲)↔find(找到/發現)。"},
   {t:"選擇題",q:"\"young\" 的相反詞是？",opts:["old","quiet","tired","powerful"],a:0,ex:"young(年輕)↔old(年老)。"},
   {t:"選擇題",q:"\"quiet\" 的相反詞是？",opts:["loud","young","strange","safe"],a:0,ex:"quiet(安靜)↔loud(大聲)。"},
   {t:"選擇題",q:"\"refuse\" 的意思是？",opts:["拒絕","回收","休息","返回"],a:0,ex:"refuse = 拒絕。"},
   {t:"選擇題",q:"\"mist\" 的中文是？",opts:["霧","錯誤","任務","肌肉"],a:0,ex:"mist = 霧。"},
   {t:"選擇題",q:"\"village\" 的意思是？",opts:["村莊","城市","山谷","勝利"],a:0,ex:"village = 村莊。"},
   {t:"選擇題",q:"\"laugh\" 的意思是？",opts:["大笑","哭泣","躺下","放開"],a:0,ex:"laugh = 大笑。"},
   {t:"是非題",q:"\"tired\" 的意思是「精力充沛的」。",opts:["正確 True","錯誤 False"],a:1,ex:"tired = 疲累的，故 False。"} ],
 [ {t:"選擇題",q:"\"tiny\" 的相反詞最接近？",opts:["huge","bright","real","together"],a:0,ex:"tiny(微小)↔huge(巨大)。"},
   {t:"選擇題",q:"\"anger\" 的中文是？",opts:["憤怒","天使","角度","答案"],a:0,ex:"anger = 憤怒。"},
   {t:"選擇題",q:"\"sorrow\" 的意思是？",opts:["悲傷","明天","箭","借"],a:0,ex:"sorrow = 悲傷。"},
   {t:"選擇題",q:"\"win\" 的相反詞是？",opts:["lose","find","hide","join"],a:0,ex:"win(贏)↔lose(輸)。"},
   {t:"選擇題",q:"\"bright\" 的意思是？",opts:["明亮的","黑暗的","沉重的","勇敢的"],a:0,ex:"bright = 明亮的。"},
   {t:"選擇題",q:"\"sunlight\" 的中文是？",opts:["陽光","週日","曬傷","向日葵"],a:0,ex:"sunlight = 陽光。"},
   {t:"選擇題",q:"\"find\" 的意思是？",opts:["找到","失去","給予","關閉"],a:0,ex:"find = 找到。"},
   {t:"是非題",q:"\"together\" 的意思是「一起」。",opts:["正確 True","錯誤 False"],a:0,ex:"together = 一起，True。"} ],
 [ {t:"選擇題",q:"\"forget\" 的相反詞是？",opts:["remember","regret","refuse","break"],a:0,ex:"forget(忘)↔remember(記)。"},
   {t:"選擇題",q:"\"regret\" 的意思是？",opts:["後悔","反映","歸還","休息"],a:0,ex:"regret = 後悔。"},
   {t:"選擇題",q:"\"strength\" 的中文是？",opts:["力量","長度","壓力","街道"],a:0,ex:"strength = 力量。"},
   {t:"選擇題",q:"\"punch\" (名詞) 的意思是？",opts:["一拳","午餐","部分","口袋"],a:0,ex:"punch = 一拳。"},
   {t:"選擇題",q:"\"fear\" 的意思是？",opts:["恐懼","公平","靠近","幾乎"],a:0,ex:"fear = 恐懼。"},
   {t:"選擇題",q:"\"blow\" (名詞) 在此指？",opts:["一擊","吹氣","藍色","綻放"],a:0,ex:"此處 blow = 一擊。"},
   {t:"選擇題",q:"\"break\" 的意思之一是？",opts:["打破","製造","攜帶","保護"],a:0,ex:"break = 打破。"},
   {t:"是非題",q:"\"refuse\" 的意思是「同意」。",opts:["正確 True","錯誤 False"],a:1,ex:"refuse = 拒絕，故 False。"} ],
 [ {t:"選擇題",q:"\"empty\" 的相反詞是？",opts:["full","hate","empty","finish"],a:0,ex:"empty(空)↔full(滿)。"},
   {t:"選擇題",q:"\"hate\" 的相反詞是？",opts:["love","smile","finish","remember"],a:0,ex:"hate(恨)↔love(愛)。"},
   {t:"選擇題",q:"\"temple\" 的中文是？",opts:["神殿","脾氣","樣板","溫度"],a:0,ex:"temple = 神殿。"},
   {t:"選擇題",q:"\"cult\" 的意思最接近？",opts:["邪教","文化","切割","線索"],a:0,ex:"cult = 邪教。"},
   {t:"選擇題",q:"\"feeling\" 的意思是？",opts:["感覺","田野","費用","填滿"],a:0,ex:"feeling = 感覺。"},
   {t:"選擇題",q:"\"finish\" 的意思是？",opts:["完成","釣魚","懲罰","飛行"],a:0,ex:"finish = 完成。"},
   {t:"選擇題",q:"\"smile\" 的中文是？",opts:["微笑","蝸牛","味道","風格"],a:0,ex:"smile = 微笑。"},
   {t:"是非題",q:"\"student\" 的意思是「學生」。",opts:["正確 True","錯誤 False"],a:0,ex:"student = 學生，True。"} ],
 [ {t:"選擇題",q:"\"choose\" 的意思是？",opts:["選擇","咀嚼","關閉","歡呼"],a:0,ex:"choose = 選擇。"},
   {t:"選擇題",q:"\"will\" (名詞) 在此指？",opts:["意志","將會","遺囑","願望"],a:0,ex:"此處 will = 意志。"},
   {t:"選擇題",q:"\"dawn\" 的中文是？",opts:["黎明","黃昏","草坪","門"],a:0,ex:"dawn = 黎明。"},
   {t:"選擇題",q:"\"shape\" 的意思是？",opts:["形狀","分享","羊","架子"],a:0,ex:"shape = 形狀。"},
   {t:"選擇題",q:"\"endless\" 的意思是？",opts:["無盡的","無用的","結局的","無畏的"],a:0,ex:"endless = 無盡的。"},
   {t:"選擇題",q:"\"greatest\" 是哪個字的最高級？",opts:["great","greaty","grease","greet"],a:0,ex:"great→greatest。"},
   {t:"選擇題",q:"\"blade\" 的中文是？",opts:["刀刃","責備","遊戲","等級"],a:0,ex:"blade = 刀刃。"},
   {t:"是非題",q:"\"tired\" 的意思是「疲累的」。",opts:["正確 True","錯誤 False"],a:0,ex:"tired = 疲累的，True。"} ],
 [ {t:"選擇題",q:"\"victory\" 的相反詞是？",opts:["defeat","king","light","fear"],a:0,ex:"victory(勝利)↔defeat(失敗)。"},
   {t:"選擇題",q:"\"king\" 的中文是？",opts:["國王","王國","善良","膝蓋"],a:0,ex:"king = 國王。"},
   {t:"選擇題",q:"\"sick\" 的意思是？",opts:["生病的","厚的","快的","安靜的"],a:0,ex:"sick = 生病的。"},
   {t:"選擇題",q:"\"rise\" 的相反詞是？",opts:["fall","raise","rest","run"],a:0,ex:"rise(升)↔fall(降)。"},
   {t:"選擇題",q:"\"light\" 在此的意思是？",opts:["光","輕的","燈","以上皆可"],a:3,ex:"light 多義：光/輕的/燈，此處主要指光。"},
   {t:"選擇題",q:"\"return\" 的意思是？",opts:["返回","重複","獎勵","拒絕"],a:0,ex:"return = 返回。"},
   {t:"選擇題",q:"\"forever\" 的意思是？",opts:["永遠","有時","以前","很快"],a:0,ex:"forever = 永遠。"},
   {t:"是非題",q:"\"brave\" 的意思是「勇敢的」。",opts:["正確 True","錯誤 False"],a:0,ex:"brave = 勇敢的，True。"} ]
];
VQ2.forEach(function(arr,i){ if(LEVELS[i]) arr.forEach(function(q){ LEVELS[i].bank.push(Object.assign({cat:"v"}, q)); }); });
